#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 F. C. Langbein <frank@langbein.org>
# SPDX-FileCopyrightText: (C) 2026 S. P. O'Neil <sean.oneil@westpoint.edu>
# SPDX-FileCopyrightText: (C) 2026 S. Schirmer <s.m.shermer@gmail.com>
# SPDX-FileCopyrightText: (C) 2026 C. A. Weidner <c.weidner@bristol.ac.uk>
# SPDX-FileCopyrightText: (C) 2026 E. A. Jonckheere <jonckhee@usc.edu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The production flags for every driver, and the BLAS environment they run in.

Read by the Makefile, as a fragment generated with ``--make``
(SERIAL_BLAS, FLAGS_<stem>[_<n>], MFLAGS_<stem>[_<n>]), and by
check_reproducible, which imports DRIVER_RUNS. A driver absent from the
table takes no production flags. --out and --jobs are not in the table;
the caller supplies them.

Usage: ``_invocations.py --make`` prints the fragment;
``_invocations.py SCRIPT [INDEX]`` prints the flags of one invocation."""

from __future__ import annotations

import sys

#: BLAS thread environment for the drivers: one thread, since the matrices
#: are small and a thread pool only slows them down. Pinning changes BLAS
#: reduction order, so results move in their last bits (well within the
#: 1e-8 the reproduction check allows).
SERIAL_BLAS_ENV = {
    "OMP_NUM_THREADS": "1",
    "OPENBLAS_NUM_THREADS": "1",
    "MKL_NUM_THREADS": "1",
}

#: driver -> the argument lists it is run with, in order; each run writes
#: different outputs.
DRIVER_RUNS: dict[str, list[list[str]]] = {
    "run_lipschitz_margin_case_study.py": [
        # --sweep adds the fidelity-vs-delta sweep and the H*_all.png figures.
        # The peers' option is do_sweep, default true, so this driver's MFLAGS
        # is deliberately unused.
        ["--sweep"],
    ],
    "run_multiparameter_case_study.py": [
        # tv_bracket_<FT>.csv covers the first --adversary controllers.
        ["--step", "lipschitz", "--adversary", "5"],
        ["--step", "angular"],
    ],
    "run_kosut_validity.py": [
        # A violation is expected, so the run must not fail on it.
        ["--n-starts", "12", "--starts", "mixed", "--allow-violations"],
        # The trajectory class writes validity_<FT>_tv.csv.
        [
            "--n-starts",
            "12",
            "--starts",
            "mixed",
            "--allow-violations",
            "--uncertainty",
            "trajectory",
        ],
    ],
    "run_time_bandwidth_bound_comparison.py": [
        # Three runs, three files: angular absorption (default), additive
        # absorption, and the trajectory uncertainty class (tab_tv).
        [],
        ["--absorption", "additive"],
        ["--uncertainty", "trajectory"],
    ],
    "run_robust_vs_nominal.py": [
        # Adds the adversarial witness columns that tab_robust needs.
        ["--adversary"],
    ],
}


def flags(script: str, index: int = 0) -> list[str]:
    """Production flags for a single invocation of ``script``.

    A driver absent from the table gives []. Raises IndexError for an
    out-of-range ``index`` rather than returning [].
    """
    runs = DRIVER_RUNS.get(script, [[]])
    if not 0 <= index < len(runs):
        raise IndexError(f"{script} has {len(runs)} invocation(s); no index {index}")
    return runs[index]


def _emit_make() -> None:
    """Write a Makefile fragment: SERIAL_BLAS, FLAGS_<stem>, FLAGS_<stem>_<n>."""
    print("# Generated by scripts/_invocations.py -- do not edit.")
    print("# Regenerated whenever that file changes; see the Makefile rule.")
    env = " ".join(f"{k}={v}" for k, v in SERIAL_BLAS_ENV.items())
    print(f"SERIAL_BLAS := {env}")
    for script, runs in sorted(DRIVER_RUNS.items()):
        if not script.endswith(".py"):
            raise ValueError(f"table key {script!r} is not a .py filename")
        stem = script[:-3]
        for i, run in enumerate(runs):
            name = f"FLAGS_{stem}" if i == 0 else f"FLAGS_{stem}_{i}"
            for tok in run:
                # The fragment is used unquoted in recipes, so '#', '$' and
                # whitespace in a flag would silently change the arguments.
                if any(c in tok for c in "#$ \t\n"):
                    raise ValueError(
                        f"{script}: argument {tok!r} needs quoting that this "
                        "fragment cannot express; keep flags simple"
                    )
            print(f"{name} := {' '.join(run)}")
            # The same settings as MATLAB/Octave name/value pairs.
            print(f"M{name} := {_matlab_args(run)}")


def _matlab_args(run: list[str]) -> str:
    """Convert a Python flag list into MATLAB name/value pairs.

    ``["--absorption", "additive"]`` becomes ``,'absorption','additive'``;
    a flag without a value becomes ``,'flag',true``. The leading comma lets a
    recipe append the result directly after its fixed arguments, and an
    empty run renders as the empty string.
    """
    out: list[str] = []
    i = 0
    while i < len(run):
        tok = run[i]
        if not tok.startswith("--"):
            raise ValueError(f"expected a --flag, got {tok!r}")
        name = tok[2:].replace("-", "_")
        if i + 1 < len(run) and not run[i + 1].startswith("--"):
            out.append(f"'{name}','{run[i + 1]}'")
            i += 2
        else:
            out.append(f"'{name}',true")
            i += 1
    return ("," + ",".join(out)) if out else ""


if __name__ == "__main__":
    if "--make" in sys.argv:
        _emit_make()
    else:
        script = sys.argv[1]
        index = int(sys.argv[2]) if len(sys.argv) > 2 else 0
        print(" ".join(flags(script, index)))
