#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 F. C. Langbein <frank@langbein.org>
# SPDX-FileCopyrightText: (C) 2026 S. P. O'Neil <sean.oneil@westpoint.edu>
# SPDX-FileCopyrightText: (C) 2026 S. Schirmer <s.m.shermer@gmail.com>
# SPDX-FileCopyrightText: (C) 2026 C. A. Weidner <c.weidner@bristol.ac.uk>
# SPDX-FileCopyrightText: (C) 2026 E. A. Jonckheere <jonckhee@usc.edu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit every number the paper quotes in prose as a LaTeX macro.

Tables and figures were already generated; the numbers in running text
were not, and were maintained by hand against a post hoc consistency
check. This closes that gap: each quantity is computed here from the same
CSVs the tables come from, and the paper refers to it by name.

Writes results/paper-xqrm/macros.tex. Every macro is defined through
\\xqdef, and the paper's preamble makes an undefined \\xq... an error, so
a number whose source disappears breaks the build instead of silently
keeping its last value.

Usage: python3 scripts/gen_paper_xqrm_macros.py [--allow-missing]
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import numpy as np
from qrobustness.kosut import effective_threshold

from _paper import col, configure, read

ROOT = Path(__file__).resolve().parents[1]

# Ensemble configuration. These are properties of the shipped problem and
# the driver invocations, not free text; they are emitted so the paper
# cannot drift from the runs.
THRESHOLD = 0.999
# The constant-margin counterexample the paper discusses. Named so a
# second one appearing does not silently change which is quoted.
WITNESS_CONTROLLER = "16"
WITNESS_STRUCTURE = "H1"
BUDGET_FACTOR = 1.05


#: Set from --allow-missing. The flag was documented and parsed but never
#: read, so a missing input aborted regardless of what the caller asked for.


class Macros:
    """Collects macro definitions and writes them out.

    Values are formatted at the precision the prose needs; the raw value
    is kept in a comment so a reader can see what was rounded.
    """

    def __init__(self):
        self.items = []

    def add(self, name, value, fmt="{:.2f}", note=""):
        if isinstance(value, str):
            text = value
        else:
            text = fmt.format(value)
        self.items.append((name, text, value, note))
        return text

    def write(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        out = [
            "% Auto-generated by scripts/gen_paper_xqrm_macros.py -- do not edit.",
            "% Every number quoted in the paper's prose is defined here and",
            "% computed from the CSVs in results/. Regenerate with",
            "%   make paper-xQRM",
            "%",
            "% \\xqdef defines a macro and refuses to redefine one, so a",
            "% duplicated name is an error rather than a silent overwrite.",
            r"\makeatletter",
            r"\newcommand{\xqdef}[2]{%",
            r"  \@ifundefined{#1}{\expandafter\gdef\csname #1\endcsname{#2}}%",
            r"    {\PackageError{xqrm}{Duplicate generated macro #1}{}}}",
            r"\makeatother",
            "",
        ]
        for name, text, raw, note in self.items:
            comment = f"  % {raw}" if not isinstance(raw, str) else ""
            if note:
                comment += f"  {note}" if comment else f"  % {note}"
            out.append(f"\\xqdef{{{name}}}{{{text}}}{comment}")
        path.write_text("\n".join(out) + "\n")
        return len(self.items)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--allow-missing",
        action="store_true",
        help="tolerate absent inputs (development only)",
    )
    ap.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="print each macro and its value",
    )
    args = ap.parse_args()
    configure(ROOT / "results", args.allow_missing)

    res = ROOT / "results"
    m = Macros()

    mp = read(res / "multiparameter-margin-python/multiparam_0.999_angular.csv")
    jg = read(res / "multiparameter-margin-python/joint_gauge_0.999.csv")
    kos = read(res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular.csv")
    kos_tv = read(
        res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular_tv.csv"
    )
    sq = read(res / "single-qubit-python/single_qubit_0.999.csv")
    deph = read(res / "lindblad-margin-python/open_margins_0.999.csv")
    amp = read(res / "lindblad-margin-python/open_amp_0.999.csv")

    # -- ensemble ------------------------------------------------------
    m.add("xqNumControllers", len(mp), "{:d}")
    m.add("xqThreshold", THRESHOLD, "{:.3f}")
    m.add("xqBudgetFactor", BUDGET_FACTOR, "{:.2f}")

    # -- Scenario J: the gauge regions against the cross-polytope -------
    # Certified inradius gain of the joint Frobenius gauge over the
    # separable cross-polytope, and the estimated (nonconvex maximum)
    # gain the certified one is a conservative reading of.
    m.add("xqGaugeInradiusGain", np.median(col(jg, "inradius_gain_cert")))
    m.add("xqGaugeInradiusGainEst", np.median(col(jg, "inradius_gain_est")))
    m.add("xqGaugeDiagGain", np.median(col(jg, "diag_gain_med")))
    m.add("xqGaugeAngDiagGain", np.median(col(jg, "ang_diag_gain")))
    m.add("xqGaugeTrajGain", np.median(col(jg, "traj_gain")))

    # -- Scenario T: cost of uniformity over trajectories --------------
    # r_0/M, the price of certifying every bounded trajectory rather than
    # a constant perturbation, per structure.
    # Axis plus diagonal directions, and the total rays iterated over the
    # ensemble; both are read off the table rather than counted by hand.
    n_dirs = len([k for k in mp[0] if re.match(r"^M_[+-]|^M_diag", k)])
    m.add("xqDirectionalDirs", n_dirs, "{:d}")
    m.add("xqDirectionalRays", n_dirs * len(mp), "{:d}")

    for i, (tag, key) in enumerate((("Drift", "H0"), ("CtrlOne", "H1"))):
        m.add(
            f"xqRZeroOverM{tag}", np.median(col(mp, f"r0_{key}") / col(mp, f"M_+e{i}"))
        )

    # -- universal-bound comparison ------------------------------------
    # The paper prints this as a range, so only its two ends are needed.
    for tag, key in (("Drift", "H0"), ("CtrlTwo", "H2")):
        m.add(f"xqKosutRatio{tag}", np.median(col(kos, f"ratio_{key}")))

    # -- single qubit against analytic truth ---------------------------
    amp_sq = [r for r in sq if r["structure"] == "amplitude"][0]
    # Saturation of the path-length bound for the commuting error: the one
    # agreement in this paragraph that the prose used to state by hand.
    _rel = abs(float(amp_sq["r_fs"]) - float(amp_sq["delta_star"])) / float(
        amp_sq["delta_star"]
    )
    m.add("xqSingleQubitFsRel", f"{_rel * 1e7:.0f}\\times10^{{-7}}")

    det = [r for r in sq if r["structure"] == "detuning"][0]
    rfs, dstar = float(det["r_fs"]), float(det["delta_star"])
    m.add("xqSingleQubitRFs", rfs, "{:.3f}")
    m.add("xqSingleQubitCoverage", 100.0 * rfs / dstar, "{:.0f}")
    m.add("xqSingleQubitRZeroCoverage", 100.0 * float(det["r0"]) / dstar, "{:.0f}")

    # -- angular continuation against the Lipschitz step ---------------
    mp_lipschitz = read(res / "multiparameter-margin-python/multiparam_0.999.csv")
    nevs_angular = np.array(
        [float(row[key]) for row in mp for key in row if key.startswith("nev_")]
    )
    nevs_lipschitz = np.array(
        [
            float(row[key])
            for row in mp_lipschitz
            for key in row
            if key.startswith("nev_")
        ]
    )
    m.add(
        "xqAngularNoMoreEvalsPct",
        100.0 * np.mean(nevs_angular <= nevs_lipschitz),
        "{:.0f}",
    )
    m.add(
        "xqAngularMedianEvalSavingPct",
        100.0 * np.median(1.0 - nevs_angular / nevs_lipschitz),
        "{:.0f}",
    )

    # -- adversarial counterexample to constant-scaling ----------------
    witnesses = read(res / "time-bandwidth-bound-python/validity_witness_0.999.csv")
    violations = [row for row in witnesses if row["violated"] == "1"]
    if not violations:
        raise SystemExit(
            "ERROR: no constant-margin counterexample recorded; the paper's "
            "claim that one exists has no evidence behind it. Rerun "
            "run_kosut_validity.py."
        )
    # The count is emitted, not asserted. A stronger adversary finding a
    # second counterexample is a result, not a build failure: the paper
    # quotes this macro, so its sentence follows the run instead of the
    # run being required to agree with the sentence. Aborting here would
    # also contradict --allow-violations, which exists precisely so more
    # counterexamples do not stop the driver.
    # The witness the paper discusses in detail, identified by name rather
    # than by being the only one present.
    named = [
        r
        for r in violations
        if r["controller"] == WITNESS_CONTROLLER and r["structure"] == WITNESS_STRUCTURE
    ]
    if len(named) != 1:
        raise SystemExit(
            f"ERROR: expected the documented witness (controller "
            f"{WITNESS_CONTROLLER}, structure {WITNESS_STRUCTURE}) among the "
            f"{len(violations)} recorded; found {len(named)}. Either the run "
            "no longer reproduces it, or the paper should discuss a different "
            "one -- do not simply relabel."
        )
    excess = named[0].get("omega_avg_excess")
    if not excess:
        raise SystemExit(
            "ERROR: violating trajectory lacks omega_avg_excess; "
            "rerun run_kosut_validity.py"
        )
    m.add("xqValidityOmegaAvgExcess", float(excess), "{:.1f}")

    # -- open system: one-step radius against the resolved crossing ----
    # For dephasing the diamond constant equals the first-order slope, so
    # the ratio is 1 up to nominal error and curvature; for amplitude
    # damping the slope is half the diamond rate, hence the factor 2.
    m.add(
        "xqAmpConservatism",
        np.median(col(amp, "amp_star") / col(amp, "r0_amp")),
        "{:.4f}",
    )
    # The one-step radius sits this far below the resolved crossing; the
    # iterated margin closes essentially all of it.
    m.add(
        "xqDephasingOneStepExcessPct",
        100.0 * (np.median(col(deph, "gamma_star") / col(deph, "r0_gamma")) - 1.0),
        "{:.2f}",
    )
    # Evaluation cost of the dephasing iteration, so the paper quotes a
    # generated count rather than a remembered one.
    m.add(
        "xqDephasingEvals", int(round(float(np.median(col(deph, "n_evals"))))), "{:d}"
    )

    # -- coherent perturbation through the open-system functional -------
    # The open-system constant covers dissipation; used on a coherent
    # structure it is much looser than the closed-system one. The paper
    # quotes the size of that gap as a reason to prefer the closed-system
    # certificate when the perturbation is known to be coherent.
    coh = read(res / "lindblad-margin-python/open_coherent_0.999.csv")
    m.add("xqOpenCoherentNum", len(coh), "{:d}")
    m.add("xqOpenCoherentDnorm", np.median(col(coh, "dnorm_unit")), "{:.0f}")
    # Constant across controllers: both constants scale with the same
    # per-interval control amplitudes, so only the norms differ.
    m.add("xqOpenCoherentLRatio", np.median(col(coh, "ratio_L")), "{:.0f}")
    m.add("xqOpenCoherentRZeroRatioMin", col(coh, "ratio_r0").min(), "{:.0f}")
    m.add("xqOpenCoherentRZeroRatioMax", col(coh, "ratio_r0").max(), "{:.0f}")
    m.add("xqOpenCoherentIteratedRatio", np.median(col(coh, "ratio_M")), "{:.2f}")

    # -- nominal-error absorption: additive vs angular ------------------
    # The additive allowance uses a threshold that is too low; the angular
    # one is the sufficient reading (triangle inequality on Choi states).
    # The absorption must cover the worst controller in the ensemble, so
    # the quoted nominal error is the maximum, not the median.
    eps0 = float(col(mp, "err").max())
    m.add("xqEpsZero", f"{eps0 * 1e5:.1f}\\times10^{{-5}}")
    m.add(
        "xqThresholdAdditive",
        effective_threshold(THRESHOLD, eps0, "additive"),
        "{:.4f}",
    )
    m.add(
        "xqThresholdAngular", effective_threshold(THRESHOLD, eps0, "angular"), "{:.5f}"
    )

    # -- threshold sweep: conservatism against the threshold ------------
    ts = read(res / "lindblad-margin-python/open_threshold_sweep.csv")
    for tag, ch in (("Dephasing", "dephasing"), ("Amp", "amp_damping")):
        sub = [r for r in ts if r["channel"] == ch and float(r["FT"]) == 0.99]
        m.add(f"xq{tag}ConservatismLooseFT", np.median(col(sub, "ratio")), "{:.3f}")
    m.add("xqLooseThreshold", 0.99, "{:.2f}")
    m.add("xqSweepNum", len({r["controller"] for r in ts}), "{:d}")

    dsw = read(res / "cnot-python/duration_sweep_0.999.csv")
    m.add(
        "xqDurationNum",
        min(sum(1 for r in dsw if r["tf"] == t) for t in {r["tf"] for r in dsw}),
        "{:d}",
    )

    # -- transfer: a synthesised CNOT ensemble --------------------------
    cn = read(res / "cnot-python/cnot_margins_0.999.csv")
    m.add("xqCnotNum", len(cn), "{:d}")

    # -- margins as a selection tool ------------------------------------
    rn = read(res / "cnot-python/robust_vs_nominal_0.999.csv")
    rob = [r for r in rn if r["kind"] == "robust"]
    nom = [r for r in rn if r["kind"] == "nominal"]
    for tag, key in (("Drift", "H0"), ("CtrlOne", "X1")):
        m.add(
            f"xqRobustGain{tag}",
            np.median(col(rob, f"M_{key}")) / np.median(col(nom, f"M_{key}")),
        )
    m.add("xqRobustNum", len(rob), "{:d}")
    # Adversarial upper witnesses on M_tv: the medians move the opposite way
    # to the static margins, which is what makes the reversal a statement
    # about the true margins rather than about certificate conservatism.
    for tag, key in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        wn = col(nom, f"mub_{key}")
        wr = col(rob, f"mub_{key}")
        m.add(f"xqRobustWitnessNom{tag}", f"{np.median(wn) * 1e2:.1f}\\times10^{{-2}}")
        m.add(f"xqRobustWitnessRob{tag}", f"{np.median(wr) * 1e2:.1f}\\times10^{{-2}}")
        m.add(f"xqRobustWitnessBelow{tag}", int((wr < np.median(wn)).sum()), "{:d}")
    # The families share synthesis seeds, so the comparison is paired.
    # A paired sign count is a real statistic; the "overlap" measure this
    # replaced changed definition with the order of the medians.
    pairs = {}
    for r in rn:
        pairs.setdefault(r["seed"], {})[r["kind"]] = r
    both = [v for v in pairs.values() if len(v) == 2]
    for name, key in (
        ("Rfs", "rfs_{}"),
        ("Adv", "mub_{}"),
        ("M", "M_{}"),
    ):
        for tag, st in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
            k = key.format(st)
            down = sum(
                1 for v in both if float(v["robust"][k]) < float(v["nominal"][k])
            )
            m.add(f"xqPaired{name}Down{tag}", down, "{:d}")
    m.add("xqPairedNum", len(both), "{:d}")

    # The sharpest instances: robustified witnesses below the nominal
    # family's median certified lower bound, so the reversal is exhibited.
    m.add(
        "xqRobustWitnessBelowRfsCtrlTwo",
        int((col(rob, "mub_X2") < np.median(col(nom, "rfs_X2"))).sum()),
        "{:d}",
    )

    # -- a larger system -------------------------------------------------
    sc = read(res / "scaling-python/scaling4q_margins_0.999.csv")
    m.add("xqScalingNum", len(sc), "{:d}")
    # Deterministic cost of the iterated margin, so the prose can compare
    # certificate classes without quoting a wall-clock that does not
    # reproduce between runs, let alone between machines.
    m.add("xqScalingEvals", int(np.median(col(sc, "n_evals_iter"))), "{:d}")

    # -- comparison with the implied margins of Berberich et al. --------
    # Joined on (controller, structure): both files cover the same
    # ensemble x structure instances.
    ber = read(res / "time-bandwidth-bound-python/berberich_comparison_0.999.csv")
    fsv = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    fs_by = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    tv_by = {r["controller"]: r for r in kos_tv}
    ratio, ktv_ratio = [], []
    for r in ber:
        key = (r["controller"], r["structure"])
        if key not in fs_by:
            continue
        mb = float(r["MB_ind"])
        ratio.append(fs_by[key] / mb)
        ktv = tv_by.get(r["controller"])
        if ktv is not None:
            ktv_ratio.append(float(ktv[f"KM_{r['structure']}"]) / mb)
    ratio = np.array(ratio)
    m.add("xqBerberichNum", len(ber), "{:d}")
    m.add("xqBerberichFsGain", np.median(ratio))
    m.add("xqBerberichFsGainMin", ratio.min())
    m.add("xqBerberichFsGainMax", ratio.max())
    if ktv_ratio:
        kr = np.array(ktv_ratio)
        m.add("xqBerberichKosutTvMin", kr.min())
        m.add("xqBerberichKosutTvMax", kr.max())

    # -- the correction's effect on the universal-bound comparison ------
    # The published (additive) ratios and the corrected (angular) ones.
    kos_add = read(res / "time-bandwidth-bound-python/kosut_comparison_0.999.csv")

    # -- the trajectory certificate against its competitors -------------
    fsv = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    fs_by = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    for tag, key in (("Drift", "H0"), ("CtrlOne", "H1"), ("CtrlTwo", "H2")):
        v = [
            fs_by[(r["controller"], key)] / float(r[f"KM_{key}"])
            for r in kos_tv
            if (r["controller"], key) in fs_by
        ]
        m.add(f"xqFsOverKosutTv{tag}", np.median(v))
    # r_FS/r_0 is structure-independent: both scale with the same speed.
    v = [
        fs_by[(r["controller"], "H0")] / float(r["r0_H0"])
        for r in mp
        if (r["controller"], "H0") in fs_by
    ]
    m.add("xqFsOverRZero", np.median(v))

    m.add("xqInradiusLTwo", np.median(col(mp, "inradius_l2")), "{:.1f}\\times10^{{-4}}")
    m.items[-1] = (
        "xqInradiusLTwo",
        f"{np.median(col(mp, 'inradius_l2')) * 1e4:.1f}\\times10^{{-4}}",
        float(np.median(col(mp, "inradius_l2"))),
        "",
    )

    # -- ensemble-wide numerical verification of every certificate ------
    # The paper claims a stress-testing harness covers each implemented
    # certificate; these macros make that claim carry its own evidence
    # (breadth, depth, and the failure count) instead of asserting it.
    # The tv_slope-only figures this block used to emit are subsumed:
    # tv_slope is one of the checks counted here.
    ver = read(res / "verification-python/verification_0.999.csv")
    m.add("xqVerifyCheckKinds", len({r["check"] for r in ver}), "{:d}")
    m.add("xqVerifyInstances", len(ver), "{:d}")
    m.add("xqVerifyProbes", sum(int(r["n"]) for r in ver), "{:d}")
    m.add("xqVerifyFailures", sum(1 - int(r["passed"]) for r in ver), "{:d}")
    # Worst observed slack as a fraction of the certified bound, over the
    # checks that report one: how close the ensemble came to a violation.
    frac = [
        float(r["max_fraction_of_bound"])
        for r in ver
        if r.get("max_fraction_of_bound") not in (None, "")
    ]
    if frac:
        m.add("xqVerifyMaxFraction", max(frac))

    # -- the price of certifying against arbitrary time variation -------
    fsv = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    fs_by2 = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    price_r0, price_fs, r0_over_ktv = [], [], []
    tv_by2 = {r["controller"]: r for r in kos_tv}
    for i, key in enumerate(("H0", "H1", "H2")):
        M = col(mp, f"M_+e{i}")
        r0 = col(mp, f"r0_{key}")
        fs = np.array([fs_by2[(r["controller"], key)] for r in mp])
        price_r0.append(np.median(M / r0))
        price_fs.append(np.median(M / fs))
        ktv = np.array([float(tv_by2[r["controller"]][f"KM_{key}"]) for r in mp])
        r0_over_ktv.append(np.median(r0 / ktv))
    m.add("xqPriceRZeroMin", min(price_r0), "{:.0f}")
    m.add("xqPriceRZeroMax", max(price_r0), "{:.0f}")
    m.add("xqPriceFsMin", min(price_fs))
    m.add("xqPriceFsMax", max(price_fs))
    m.add("xqRZeroOverKosutTvDrift", r0_over_ktv[0])
    m.add("xqRZeroOverKosutTvCtrlOne", r0_over_ktv[1])
    m.add("xqRZeroOverKosutTvCtrlTwo", r0_over_ktv[2])

    # -- directional anisotropy of the certified region -----------------
    dirs = [k[2:] for k in mp[0] if k.startswith("M_")]
    Md = np.array([[float(r[f"M_{d}"]) for d in dirs] for r in mp])
    aniso = Md.max(axis=1) / Md.min(axis=1)
    m.add("xqAnisotropyMedian", np.median(aniso))
    m.add("xqAnisotropyMax", aniso.max())

    # -- adversarial brackets on the trajectory margin ------------------
    tvb = read(res / "multiparameter-margin-python/tv_bracket_0.999.csv")
    frac = col(tvb, "m_ub") / col(tvb, "M_const")
    m.add("xqTvBracketProbed", len(tvb), "{:d}")
    m.add("xqTvBracketFracMin", frac.min(), "{:.1f}")
    m.add("xqTvBracketFracMax", frac.max(), "{:.1f}")

    # -- the universal-bound violation, found adversarially -------------
    val = read(res / "time-bandwidth-bound-python/validity_0.999.csv")
    # Three grid levels, so "reachable only by sub-interval refinement"
    # is shown rather than asserted: the control grid stays above FT and
    # only the refinements dip below it.
    # Attacks behind the r_FS sweep: rows x (grids x budget factors), so the
    # count follows the protocol instead of being restated in the prose.
    fsval = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    n_fmin = len([k for k in fsval[0] if k.startswith("Fmin_")])
    m.add("xqFsAttacks", len(fsval) * n_fmin, "{:d}")

    m.add("xqValidityFminGrid", min(float(r["Fmin_m1_grid"]) for r in val), "{:.6f}")
    m.add("xqValidityFminCoarse", min(float(r["Fmin_m1_x4"]) for r in val), "{:.6f}")
    m.add("xqValidityFminFine", min(float(r["Fmin_m1_x16"]) for r in val), "{:.6f}")
    m.add("xqValidityViolations", sum(int(r["violated"]) for r in val), "{:d}")

    # -- against the implied margins of Berberich et al. ----------------
    # -- the synthesised CNOT ensemble against the universal bound ------
    kk = [np.median(col(cn, f"M_{k}") / col(cn, f"KM_{k}")) for k in ("H0", "X1", "X2")]
    m.add("xqCnotOverKosutMin", min(kk))
    m.add("xqCnotOverKosutMax", max(kk))
    m.add("xqCnotFsOverRZero", np.median(col(cn, "rfs_X1") / col(cn, "r0_X1")))

    tvb = read(res / "multiparameter-margin-python/tv_bracket_0.999.csv")

    # -- the two-sided bracket on the trajectory margin -----------------
    # Certified lower ends (r_FS) and adversarial upper ends (m_ub) on
    # the probed controllers; the interval is strictly positive.
    lo = np.array([fs_by2[(r["controller"], r["structure"])] for r in tvb])
    hi = col(tvb, "m_ub")
    m.add("xqTvBracketLowMin", lo.min() * 1e3, "{:.1f}")
    m.add("xqTvBracketLowMax", lo.max() * 1e3, "{:.1f}")
    m.add("xqTvBracketHighMin", hi.min() * 1e3, "{:.1f}")
    m.add("xqTvBracketHighMax", hi.max() * 1e3, "{:.1f}")

    # -- how much the absorption choice actually moves ------------------
    # The share of the angle budget the nominal error consumes, and the
    # resulting reduction in the implied universal-bound margin.
    th_T = math.acos(THRESHOLD)
    th_0 = math.acos(1.0 - eps0)
    m.add("xqAbsorptionAngleShare", 100.0 * th_0 / th_T, "{:.0f}")
    dec = [
        100.0
        * (1.0 - np.median(col(kos, f"KM_{k}")) / np.median(col(kos_add, f"KM_{k}")))
        for k in ("H0", "H1", "H2")
    ]
    m.add("xqAbsorptionMarginDropMin", min(dec), "{:.0f}")
    m.add("xqAbsorptionMarginDropMax", max(dec), "{:.0f}")

    out = res / "paper-xqrm" / "macros.tex"
    n = m.write(out)
    if args.show:
        for name, text, raw, _ in m.items:
            print(f"  \\{name:28s} = {text:>10s}   ({raw})")
    print(f"wrote {n} macros to {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
