#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 F. C. Langbein <frank@langbein.org>
# SPDX-FileCopyrightText: (C) 2026 S. P. O'Neil <sean.oneil@westpoint.edu>
# SPDX-FileCopyrightText: (C) 2026 S. Schirmer <s.m.shermer@gmail.com>
# SPDX-FileCopyrightText: (C) 2026 C. A. Weidner <c.weidner@bristol.ac.uk>
# SPDX-FileCopyrightText: (C) 2026 E. A. Jonckheere <jonckhee@usc.edu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write every number the xQRM paper quotes in prose as a LaTeX macro.

Inputs: the driver CSVs under results/ (multiparameter-margin-python,
time-bandwidth-bound-python, single-qubit-python, lindblad-margin-python,
cnot-python, scaling-python, verification-python, state-examples-python,
algorithm-tests-python, bracket-audit-python incl. environment.json).

Output: results/paper-xqrm/macros.tex, one \\xqdef{name}{value} per number
with the unrounded value in a trailing comment. \\xqdef refuses to redefine
a name, so a duplicated macro is a LaTeX error. Macros emitted but cited
nowhere are reported by check_reproducible.

Options: --allow-missing tolerates absent inputs; --print lists each macro.

Usage: python3 scripts/gen_paper_xqrm_macros.py [--allow-missing] [--print]"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

import numpy as np
from qrobustness.kosut import effective_threshold

from _paper import col, configure, read

ROOT = Path(__file__).resolve().parents[1]

# Ensemble configuration, as used by the driver invocations.
THRESHOLD = 0.999

#: Joint uncertainty dimension p of the main ensemble: drift and two
#: multiplicative control errors.
N_PARAMS = 3
# The constant-margin counterexample the paper discusses (controller, structure).
WITNESS_CONTROLLER = "16"
WITNESS_STRUCTURE = "H1"
BUDGET_FACTOR = 1.05


# Reported extremes round outward, so a quoted range contains all the data.
def _floor_to(x: float, places: int = 0) -> float:
    """Round down, so that a quoted lower end never overstates the data."""
    f = 10.0**places
    return math.floor(x * f) / f


def _ceil_to(x: float, places: int = 0) -> float:
    """Round up, so that a quoted upper bound remains a bound."""
    f = 10.0**places
    return math.ceil(x * f) / f


def _sci(x: float, places: int = 1, *, up: bool = True) -> str:
    """``x`` as LaTeX scientific notation, with the exponent taken from ``x``.

    The mantissa rounds away from zero by default, so an upper bound remains
    an upper bound at the printed precision; pass ``up=False`` for a lower
    end.
    """
    if x == 0.0:
        return "0"
    exp = math.floor(math.log10(abs(x)))
    mant = x / 10.0**exp
    f = 10.0**places
    mant = (math.ceil(mant * f) if up else math.floor(mant * f)) / f
    # Rounding up can carry the mantissa as far as 10.0; renormalise.
    if abs(mant) >= 10.0:
        mant /= 10.0
        exp += 1
    return f"{mant:.{places}f}\\times10^{{{exp}}}"


def _is_nonzero(raw) -> bool:
    """True when the underlying quantity is a number and is not zero."""
    return isinstance(raw, (int, float)) and not isinstance(raw, bool) and raw != 0


def _renders_as_zero(text: str) -> bool:
    """True when the leading number in a rendered macro is zero.

    Inspects only the mantissa: ``0.0\\times10^{-6}`` is zero however small
    the exponent, while ``4.8\\times10^{-9}`` is not.
    """
    m = re.match(r"\s*-?([0-9]+(?:\.[0-9]+)?)", text)
    return m is not None and float(m.group(1)) == 0.0


class Macros:
    """Assembles macro definitions and writes them out.

    Values are formatted at the precision the prose needs; the raw value
    is retained in a comment so a reader can see what was rounded.
    """

    def __init__(self):
        self.items = []

    def add(self, name, value, fmt="{:.2f}", note="", raw=None):
        """Store a macro.

        ``raw`` is the underlying number when ``value`` is an already
        rendered string; write() uses it for the zero-render check.
        """
        if isinstance(value, str):
            text = value
        else:
            text = fmt.format(value)
        self.items.append((name, text, value if raw is None else raw, note))
        return text

    def write(self, path: Path):
        path.parent.mkdir(parents=True, exist_ok=True)
        out = [
            "% Auto-generated by scripts/gen_paper_xqrm_macros.py -- do not edit.",
            "% Every number quoted in the paper's prose is defined here and",
            "% computed from the CSVs in results/. Regenerate with",
            "%   make sync-xQRM",
            "%",
            "% \\xqdef defines a macro and refuses to redefine one, so a",
            "% duplicated name is an error rather than a silent overwrite.",
            r"\makeatletter",
            r"\newcommand{\xqdef}[2]{%",
            r"  \@ifundefined{#1}{\expandafter\gdef\csname #1\endcsname{#2}}%",
            r"    {\PackageError{xqrm}{Duplicate generated macro #1}{}}}",
            r"\makeatother",
            "",
        ]
        for name, text, raw, note in self.items:
            # A nonzero quantity must not print as zero (a fixed power-of-ten
            # scale that no longer fits the value).
            if _renders_as_zero(text) and _is_nonzero(raw):
                raise SystemExit(
                    f"ERROR: macro {name} renders as {text!r} but its value "
                    f"is {raw!r}. The printed scale no longer matches the "
                    "quantity; use _sci() or choose a scale that fits."
                )
            comment = f"  % {raw}" if not isinstance(raw, str) else ""
            if note:
                comment += f"  {note}" if comment else f"  % {note}"
            out.append(f"\\xqdef{{{name}}}{{{text}}}{comment}")
        path.write_text("\n".join(out) + "\n")
        return len(self.items)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--allow-missing",
        action="store_true",
        help="tolerate absent inputs (development only)",
    )
    ap.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="print each macro and its value",
    )
    args = ap.parse_args()
    configure(ROOT / "results", args.allow_missing)

    res = ROOT / "results"
    m = Macros()

    mp = read(res / "multiparameter-margin-python/multiparam_0.999_angular.csv")
    jg = read(res / "multiparameter-margin-python/joint_gauge_0.999.csv")
    kos = read(res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular.csv")
    kos_tv = read(
        res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular_tv.csv"
    )
    sq = read(res / "single-qubit-python/single_qubit_0.999.csv")
    deph = read(res / "lindblad-margin-python/open_margins_0.999.csv")
    amp = read(res / "lindblad-margin-python/open_amp_0.999.csv")

    # -- ensemble ------------------------------------------------------
    m.add("xqNumControllers", len(mp), "{:d}")
    m.add("xqThreshold", THRESHOLD, "{:.3f}")
    m.add("xqBudgetFactor", BUDGET_FACTOR, "{:.2f}")

    # -- Scenario J: the gauge regions versus the cross-polytope -------
    # Inradius gain of the joint gauge (C_joint) over the separable
    # cross-polytope: certified and estimated (nonconvex peak), medians.
    m.add("xqGaugeInradiusGain", np.median(col(jg, "inradius_gain_cert")))
    m.add("xqGaugeInradiusGainEst", np.median(col(jg, "inradius_gain_est")))
    m.add("xqGaugeDiagGain", np.median(col(jg, "diag_gain_med")))
    m.add("xqGaugeAngDiagGain", np.median(col(jg, "ang_diag_gain")))
    m.add("xqGaugeTrajGain", np.median(col(jg, "traj_gain")))
    # The gain is an l1-over-l2 ratio, so its ceiling is sqrt(p); percentage
    # of that ceiling reached by the largest diagonal gain.
    m.add("xqGaugeGainCeiling", np.sqrt(N_PARAMS))
    m.add(
        "xqGaugeGainAttainedPct",
        100.0 * col(jg, "diag_gain_max").max() / np.sqrt(N_PARAMS),
        "{:.0f}",
    )

    # -- Scenario T: cost of uniformity across trajectories --------------
    # Number of directions (axis plus diagonal) and total rays iterated;
    # median r_0/M per structure.
    n_dirs = len([k for k in mp[0] if re.match(r"^M_[+-]|^M_diag", k)])
    m.add("xqDirectionalDirs", n_dirs, "{:d}")
    m.add("xqDirectionalRays", n_dirs * len(mp), "{:d}")

    for i, (tag, key) in enumerate((("Drift", "H0"), ("CtrlOne", "H1"))):
        m.add(
            f"xqRZeroOverM{tag}", np.median(col(mp, f"r0_{key}") / col(mp, f"M_+e{i}"))
        )

    # -- universal-bound comparison ------------------------------------
    # Median M/M^K (angular absorption) for the two ends of the quoted range.
    for tag, key in (("Drift", "H0"), ("CtrlTwo", "H2")):
        m.add(f"xqKosutRatio{tag}", np.median(col(kos, f"ratio_{key}")))

    # -- single qubit against analytic truth ---------------------------
    amp_sq = [r for r in sq if r["structure"] == "amplitude"][0]
    # Relative gap |r_FS - delta*|/delta* for the commuting (amplitude) error;
    # r_FS and the r_FS, r_0 coverage of delta* for detuning.
    _rel = abs(float(amp_sq["r_fs"]) - float(amp_sq["delta_star"])) / float(
        amp_sq["delta_star"]
    )
    m.add("xqSingleQubitFsRel", f"{_rel * 1e7:.0f}\\times10^{{-7}}", raw=_rel)

    det = [r for r in sq if r["structure"] == "detuning"][0]
    rfs, dstar = float(det["r_fs"]), float(det["delta_star"])
    m.add("xqSingleQubitRFs", rfs, "{:.3f}")
    m.add("xqSingleQubitCoverage", 100.0 * rfs / dstar, "{:.0f}")
    m.add("xqSingleQubitRZeroCoverage", 100.0 * float(det["r0"]) / dstar, "{:.0f}")

    # -- angular continuation versus the Lipschitz step ---------------
    # Share of rays where the angular rule needs no more evaluations, and the
    # median evaluation saving.
    mp_lipschitz = read(res / "multiparameter-margin-python/multiparam_0.999.csv")
    nevs_angular = np.array(
        [float(row[key]) for row in mp for key in row if key.startswith("nev_")]
    )
    nevs_lipschitz = np.array(
        [
            float(row[key])
            for row in mp_lipschitz
            for key in row
            if key.startswith("nev_")
        ]
    )
    m.add(
        "xqAngularNoMoreEvalsPct",
        100.0 * np.mean(nevs_angular <= nevs_lipschitz),
        "{:.0f}",
    )
    m.add(
        "xqAngularMedianEvalSavingPct",
        100.0 * np.median(1.0 - nevs_angular / nevs_lipschitz),
        "{:.0f}",
    )

    # -- adversarial counterexample against constant-scaling ----------------
    witnesses = read(res / "time-bandwidth-bound-python/validity_witness_0.999.csv")
    violations = [row for row in witnesses if row["violated"] == "1"]
    if not violations:
        raise SystemExit(
            "ERROR: no constant-margin counterexample recorded; the paper's "
            "claim that one exists has no evidence behind it. Rerun "
            "run_kosut_validity.py."
        )
    # The witness the paper treats in detail must be among the violations;
    # its time-averaged frequency excess is emitted.
    named = [
        r
        for r in violations
        if r["controller"] == WITNESS_CONTROLLER and r["structure"] == WITNESS_STRUCTURE
    ]
    if len(named) != 1:
        raise SystemExit(
            f"ERROR: expected the documented witness (controller "
            f"{WITNESS_CONTROLLER}, structure {WITNESS_STRUCTURE}) among the "
            f"{len(violations)} recorded; found {len(named)}. Either the run "
            "does not reproduce it, or the paper should discuss a different "
            "one -- do not simply relabel."
        )
    excess = named[0].get("omega_avg_excess")
    if not excess:
        raise SystemExit(
            "ERROR: violating trajectory lacks omega_avg_excess; "
            "rerun run_kosut_validity.py"
        )
    m.add("xqValidityOmegaAvgExcess", float(excess), "{:.1f}")

    # -- open system: one-step radius versus the resolved crossing ----
    # Median gamma*/r_0 for amplitude damping.
    m.add(
        "xqAmpConservatism",
        np.median(col(amp, "amp_star") / col(amp, "r0_amp")),
        "{:.4f}",
    )
    # Dephasing: max over controllers of gamma*/r_0 - 1 in percent, rounded
    # up (the prose states it as a bound over every controller).
    m.add(
        "xqDephasingOneStepExcessPct",
        _ceil_to(
            100.0 * (col(deph, "gamma_star") / col(deph, "r0_gamma") - 1.0).max(), 3
        ),
        "{:.3f}",
    )
    # Median number of fidelity evaluations of the dephasing iteration.
    m.add(
        "xqDephasingEvals", int(round(float(np.median(col(deph, "n_evals"))))), "{:d}"
    )

    # -- coherent perturbation via the open-system functional -------
    # Coherent structures certified through the open-system constant: count,
    # median diamond norm of the unit generator, and open/closed ratios of
    # L, r_0 (range) and M.
    coh = read(res / "lindblad-margin-python/open_coherent_0.999.csv")
    m.add("xqOpenCoherentNum", len(coh), "{:d}")
    m.add("xqOpenCoherentDnorm", np.median(col(coh, "dnorm_unit")), "{:.0f}")
    m.add("xqOpenCoherentLRatio", np.median(col(coh, "ratio_L")), "{:.0f}")
    m.add(
        "xqOpenCoherentRZeroRatioMin", _floor_to(col(coh, "ratio_r0").min()), "{:.0f}"
    )
    m.add("xqOpenCoherentRZeroRatioMax", _ceil_to(col(coh, "ratio_r0").max()), "{:.0f}")
    m.add("xqOpenCoherentIteratedRatio", np.median(col(coh, "ratio_M")), "{:.2f}")

    # -- nominal-error absorption: additive vs angular ------------------
    # Largest nominal error eps_0 over the ensemble and the effective
    # thresholds under additive and angular absorption.
    eps0 = float(col(mp, "err").max())
    m.add("xqEpsZero", f"{eps0 * 1e5:.1f}\\times10^{{-5}}", raw=eps0)
    m.add(
        "xqThresholdAdditive",
        effective_threshold(THRESHOLD, eps0, "additive"),
        "{:.4f}",
    )
    m.add(
        "xqThresholdAngular", effective_threshold(THRESHOLD, eps0, "angular"), "{:.5f}"
    )

    # -- the accuracy cost of certifying a diamond norm --------------
    # Largest relative inflation of the certified diamond norm, largest
    # deviation from the closed form, and the largest n_qubits with one.
    dnc = read(res / "lindblad-margin-python/dnorm_certificates.csv")
    m.add("xqDnormInflationMax", _sci(max(float(r["rel_inflation"]) for r in dnc)))
    dev = [float(r["dev_closed_form"]) for r in dnc if r["dev_closed_form"] != ""]
    m.add("xqDnormClosedFormDev", _sci(max(dev)))
    m.add(
        "xqDnormFamilySizeMax",
        max(int(r["n_qubits"]) for r in dnc if r["closed_form"]),
        "{:d}",
    )

    # -- threshold sweep: conservatism at the loose threshold F_T = 0.99 --
    ts = read(res / "lindblad-margin-python/open_threshold_sweep.csv")
    for tag, ch in (("Dephasing", "dephasing"), ("Amp", "amp_damping")):
        sub = [r for r in ts if r["channel"] == ch and float(r["FT"]) == 0.99]
        m.add(f"xq{tag}ConservatismLooseFT", np.median(col(sub, "ratio")), "{:.3f}")
    m.add("xqLooseThreshold", 0.99, "{:.2f}")
    m.add("xqSweepNum", len({r["controller"] for r in ts}), "{:d}")

    dsw = read(res / "cnot-python/duration_sweep_0.999.csv")
    m.add(
        "xqDurationNum",
        min(sum(1 for r in dsw if r["tf"] == t) for t in {r["tf"] for r in dsw}),
        "{:d}",
    )

    # -- transfer: a synthesised CNOT ensemble --------------------------
    cn = read(res / "cnot-python/cnot_margins_0.999.csv")
    m.add("xqCnotNum", len(cn), "{:d}")

    # -- margins as a selection tool ------------------------------------
    rn = read(res / "cnot-python/robust_vs_nominal_0.999.csv")
    rob = [r for r in rn if r["kind"] == "robust"]
    nom = [r for r in rn if r["kind"] == "nominal"]
    for tag, key in (("Drift", "H0"), ("CtrlOne", "X1")):
        m.add(
            f"xqRobustGain{tag}",
            np.median(col(rob, f"M_{key}")) / np.median(col(nom, f"M_{key}")),
        )
    m.add("xqRobustNum", len(rob), "{:d}")
    # Median adversarial witnesses m_adv per family, and the number of robust
    # controllers whose m_adv lies below the nominal median.
    for tag, key in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        wn = col(nom, f"madv_{key}")
        wr = col(rob, f"madv_{key}")
        m.add(
            f"xqRobustWitnessNom{tag}",
            f"{np.median(wn) * 1e2:.1f}\\times10^{{-2}}",
            raw=float(np.median(wn)),
        )
        m.add(
            f"xqRobustWitnessRob{tag}",
            f"{np.median(wr) * 1e2:.1f}\\times10^{{-2}}",
            raw=float(np.median(wr)),
        )
        m.add(f"xqRobustWitnessBelow{tag}", int((wr < np.median(wn)).sum()), "{:d}")
    # Families share synthesis seeds: paired counts of pairs where the robust
    # r_FS, m_adv and M are below the nominal ones.
    pairs = {}
    for r in rn:
        pairs.setdefault(r["seed"], {})[r["kind"]] = r
    both = [v for v in pairs.values() if len(v) == 2]
    for name, key in (
        ("Rfs", "rfs_{}"),
        ("Adv", "madv_{}"),
        ("M", "M_{}"),
    ):
        for tag, st in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
            k = key.format(st)
            down = sum(
                1 for v in both if float(v["robust"][k]) < float(v["nominal"][k])
            )
            m.add(f"xqPaired{name}Down{tag}", down, "{:d}")
    m.add("xqPairedNum", len(both), "{:d}")

    # Pairs whose robust m_adv lies below the paired nominal r_FS.
    for tag, k in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        paired = sum(
            1
            for v in both
            if float(v["robust"][f"madv_{k}"]) < float(v["nominal"][f"rfs_{k}"])
        )
        m.add(f"xqRobustWitnessBelowPairedRfs{tag}", paired, "{:d}")

    # Pairs with robust M above nominal M_upper, and of those the pairs whose
    # robust m_adv is also below nominal r_FS (the reversals), per structure.
    for tag, k in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        static = [
            v
            for v in both
            if float(v["robust"][f"M_{k}"]) > float(v["nominal"][f"Mupper_{k}"])
        ]
        rev = [
            v
            for v in static
            if float(v["robust"][f"madv_{k}"]) < float(v["nominal"][f"rfs_{k}"])
        ]
        m.add(f"xqStaticAboveUpper{tag}", len(static), "{:d}")
        m.add(f"xqReversalPairs{tag}", len(rev), "{:d}")
    # Median paired r_FS ratio; asserts r_FS ratio = budget ratio / area
    # ratio pair by pair.
    for tag, k in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        prod = np.array(
            [
                (float(v["robust"]["budget"]) / float(v["nominal"]["budget"]))
                / (float(v["robust"][f"area_{k}"]) / float(v["nominal"][f"area_{k}"]))
                for v in both
            ]
        )
        rfs = np.array(
            [
                float(v["robust"][f"rfs_{k}"]) / float(v["nominal"][f"rfs_{k}"])
                for v in both
            ]
        )
        m.add(f"xqPairedRfsRatio{tag}", np.median(rfs))
        assert np.max(np.abs(prod - rfs) / rfs) < 1e-12, "paired factorisation"

    # Paired robust/nominal ratio of the toggling-frame coherent sum
    # (cancel_*): median and number of pairs where it decreases.
    for tag, k in (("Drift", "H0"), ("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        ratio = np.array(
            [
                float(v["robust"][f"cancel_{k}"]) / float(v["nominal"][f"cancel_{k}"])
                for v in both
            ]
        )
        m.add(f"xqRobustCancelRatio{tag}", np.median(ratio))
        m.add(f"xqRobustCancelDown{tag}", int((ratio < 1.0).sum()), "{:d}")

    # Witnesses re-evaluated through the independent expm route: count and
    # number below F_T.
    recheck = [
        float(r[f"madvF_{k}"])
        for r in rn
        for k in ("X1", "X2")
        if r.get(f"madvF_{k}") not in (None, "")
        and not np.isnan(float(r[f"madvF_{k}"]))
    ]
    m.add("xqWitnessRecheckNum", len(recheck), "{:d}")
    m.add(
        "xqWitnessRecheckViolating",
        int(sum(1 for f in recheck if f < THRESHOLD)),
        "{:d}",
    )
    # Smallest slack F_T - F over the rechecked witnesses, floored.
    m.add(
        "xqWitnessRecheckSlack",
        f"{_floor_to((THRESHOLD - max(recheck)) * 1e8, 1):.1f}\\times10^{{-8}}",
        raw=THRESHOLD - max(recheck),
    )

    # r_FS = angle budget / speed, with speed proportional to the pulse area
    # ||u_j||_1 for a multiplicative control structure: median robust/nominal
    # budget ratio, area ratio per structure, and pairs whose area grew.
    def _angle_budget(rows):
        return np.arccos(THRESHOLD) - np.arccos(np.minimum(1.0, 1.0 - col(rows, "err")))

    bud_nom, bud_rob = _angle_budget(nom), _angle_budget(rob)
    m.add("xqRobustBudgetRatio", np.median(bud_rob / bud_nom))
    for tag, k in (("CtrlOne", "X1"), ("CtrlTwo", "X2")):
        area = (bud_rob / col(rob, f"rfs_{k}")) / (bud_nom / col(nom, f"rfs_{k}"))
        m.add(f"xqRobustAreaRatio{tag}", np.median(area))
        m.add(f"xqRobustAreaUp{tag}", int((area > 1.0).sum()), "{:d}")

    # -- a larger system -------------------------------------------------
    sc = read(res / "scaling-python/scaling4q_margins_0.999.csv")
    m.add("xqScalingNum", len(sc), "{:d}")
    # Median evaluation count of the iterated margin.
    m.add("xqScalingEvals", int(np.median(col(sc, "n_evals_iter"))), "{:d}")

    # Decade of the nominal error 1 - F (must be a single one).
    nom = 1.0 - col(sc, "fid")
    exps = {int(np.floor(np.log10(v))) for v in nom}
    if len(exps) != 1:
        raise SystemExit(
            f"ERROR: nominal errors span decades {sorted(exps)}; the caption's "
            "single order of magnitude would be wrong"
        )
    m.add("xqScalingNomErrExp", exps.pop(), "{:d}")
    # Relative spread of the drift ratio r_FS/M^K_tv over the ensemble.
    dr = col(sc, "rfs_H0") / col(sc, "KMtv_H0")
    m.add(
        "xqScalingDriftFlatRel",
        f"{(dr.max() - dr.min()) / np.median(dr) * 1e6:.1f}\\times10^{{-6}}",
        raw=float((dr.max() - dr.min()) / np.median(dr)),
    )

    # -- comparison against the implied margins of Berberich et al. --------
    # r_FS/M^B (median and outward range) and M^K_tv/M^B (outward range),
    # joined on (controller, structure).
    ber = read(res / "time-bandwidth-bound-python/berberich_comparison_0.999.csv")
    fsv = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    fs_by = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    tv_by = {r["controller"]: r for r in kos_tv}
    ratio, ktv_ratio = [], []
    for r in ber:
        key = (r["controller"], r["structure"])
        if key not in fs_by:
            continue
        mb = float(r["MB_ind"])
        ratio.append(fs_by[key] / mb)
        ktv = tv_by.get(r["controller"])
        if ktv is not None:
            ktv_ratio.append(float(ktv[f"KM_{r['structure']}"]) / mb)
    ratio = np.array(ratio)
    m.add("xqBerberichNum", len(ber), "{:d}")
    m.add("xqBerberichFsGain", np.median(ratio))
    m.add("xqBerberichFsGainMin", _floor_to(ratio.min(), 2))
    m.add("xqBerberichFsGainMax", _ceil_to(ratio.max(), 2))
    if ktv_ratio:
        kr = np.array(ktv_ratio)
        m.add("xqBerberichKosutTvMin", _floor_to(kr.min(), 2))
        m.add("xqBerberichKosutTvMax", _ceil_to(kr.max(), 2))

    # -- additive-absorption universal-bound comparison (used further below) --
    kos_add = read(res / "time-bandwidth-bound-python/kosut_comparison_0.999.csv")

    # -- the trajectory certificate versus its competitors -------------
    fs_by = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    for tag, key in (("Drift", "H0"), ("CtrlOne", "H1"), ("CtrlTwo", "H2")):
        v = [
            fs_by[(r["controller"], key)] / float(r[f"KM_{key}"])
            for r in kos_tv
            if (r["controller"], key) in fs_by
        ]
        m.add(f"xqFsOverKosutTv{tag}", np.median(v))
    # Median r_FS/M^K_tv per structure, and median r_FS/r_0 (structure-independent).
    v = [
        fs_by[(r["controller"], "H0")] / float(r["r0_H0"])
        for r in mp
        if (r["controller"], "H0") in fs_by
    ]
    m.add("xqFsOverRZero", np.median(v))
    # Limit of r_FS/r_0 for an exact gate: sqrt(1 - F_T^2) arccos(F_T) / (1 - F_T).
    m.add(
        "xqFsOverRZeroLimit",
        np.sqrt(1.0 - THRESHOLD**2) * np.arccos(THRESHOLD) / (1.0 - THRESHOLD),
    )

    # Median l2 inradius of the certified set, in units of 10^-4.
    m.add("xqInradiusLTwo", np.median(col(mp, "inradius_l2")), "{:.1f}\\times10^{{-4}}")
    m.items[-1] = (
        "xqInradiusLTwo",
        f"{np.median(col(mp, 'inradius_l2')) * 1e4:.1f}\\times10^{{-4}}",
        float(np.median(col(mp, "inradius_l2"))),
        "",
    )

    # -- ensemble-wide numerical check of every certificate ------
    # Number of check kinds, instances, probes and failures.
    ver = read(res / "verification-python/verification_0.999.csv")
    m.add("xqVerifyCheckKinds", len({r["check"] for r in ver}), "{:d}")
    m.add("xqVerifyInstances", len(ver), "{:d}")
    m.add("xqVerifyProbes", sum(int(r["n"]) for r in ver), "{:d}")
    m.add("xqVerifyFailures", sum(1 - int(r["passed"]) for r in ver), "{:d}")
    # Largest observed value as a fraction of its certified bound.
    frac = [
        float(r["max_fraction_of_bound"])
        for r in ver
        if r.get("max_fraction_of_bound") not in (None, "")
    ]
    if frac:
        m.add("xqVerifyMaxFraction", max(frac))

    # Largest tol of the trajectory-certificate check (cross-route fidelity
    # discrepancy plus unitarity defect).
    tol_tc = [float(r["tol"]) for r in ver if r["check"] == "trajectory_certificate"]
    m.add(
        "xqVerifyCrossRouteTol",
        f"{max(tol_tc) * 1e14:.1f}\\times10^{{-14}}",
        raw=max(tol_tc),
    )

    # -- resolved static margin versus the trajectory lower certificates
    # Range over structures of median M/r_0 and M/r_FS, and median r_0/M^K_tv
    # per structure. (Not a measure of trajectory-certificate conservatism.)
    fs_by2 = {(r["controller"], r["structure"]): float(r["r_fs"]) for r in fsv}
    price_r0, price_fs, r0_over_ktv = [], [], []
    tv_by2 = {r["controller"]: r for r in kos_tv}
    for i, key in enumerate(("H0", "H1", "H2")):
        M = col(mp, f"M_+e{i}")
        r0 = col(mp, f"r0_{key}")
        fs = np.array([fs_by2[(r["controller"], key)] for r in mp])
        price_r0.append(np.median(M / r0))
        price_fs.append(np.median(M / fs))
        ktv = np.array([float(tv_by2[r["controller"]][f"KM_{key}"]) for r in mp])
        r0_over_ktv.append(np.median(r0 / ktv))
    m.add("xqPriceRZeroMin", _floor_to(min(price_r0)), "{:.0f}")
    m.add("xqPriceRZeroMax", _ceil_to(max(price_r0)), "{:.0f}")
    m.add("xqPriceFsMin", _floor_to(min(price_fs), 2))
    m.add("xqPriceFsMax", _ceil_to(max(price_fs), 2))
    m.add("xqRZeroOverKosutTvDrift", r0_over_ktv[0])
    m.add("xqRZeroOverKosutTvCtrlOne", r0_over_ktv[1])
    m.add("xqRZeroOverKosutTvCtrlTwo", r0_over_ktv[2])

    # -- directional anisotropy of the certified set -----------------
    # max/min of M over directions per controller: median and maximum.
    dirs = [k[2:] for k in mp[0] if k.startswith("M_")]
    Md = np.array([[float(r[f"M_{d}"]) for d in dirs] for r in mp])
    aniso = Md.max(axis=1) / Md.min(axis=1)
    m.add("xqAnisotropyMedian", np.median(aniso))
    m.add("xqAnisotropyMax", _ceil_to(aniso.max(), 2))

    # -- adversarial brackets around the trajectory margin ------------------
    # Number probed and outward range of m_adv/M.
    tvb = read(res / "multiparameter-margin-python/tv_bracket_0.999.csv")
    frac = col(tvb, "m_adv") / col(tvb, "M_const")
    m.add("xqTvBracketProbed", len(tvb), "{:d}")
    m.add("xqTvBracketFracMin", _floor_to(frac.min(), 2), "{:.2f}")
    m.add("xqTvBracketFracMax", _ceil_to(frac.max(), 2), "{:.2f}")

    # -- the universal-bound violation, located adversarially -------------
    val = read(res / "time-bandwidth-bound-python/validity_0.999.csv")
    # Number of attacks behind the r_FS sweep: rows x (grids x budget factors).
    n_fmin = len([k for k in fsv[0] if k.startswith("Fmin_")])
    m.add("xqFsAttacks", len(fsv) * n_fmin, "{:d}")

    # Smallest fidelity found on the control grid and its x4, x16 refinements.
    m.add("xqValidityFminGrid", min(float(r["Fmin_m1_grid"]) for r in val), "{:.6f}")
    m.add("xqValidityFminCoarse", min(float(r["Fmin_m1_x4"]) for r in val), "{:.6f}")
    m.add("xqValidityFminFine", min(float(r["Fmin_m1_x16"]) for r in val), "{:.6f}")
    # The prose is written for exactly one violation; any other count stops.
    n_viol = sum(int(r["violated"]) for r in val)
    if n_viol != 1:
        raise SystemExit(
            f"ERROR: the constant-class attack found {n_viol} violations, not 1. "
            "The time-variation paragraph of the xQRM paper is written for exactly one (singular "
            "noun, named structure and controller) and must be rewritten before "
            "this macro can be regenerated."
        )
    m.add("xqValidityViolations", n_viol, "{:d}")

    # -- the synthesised CNOT ensemble versus the universal bound ------
    # Range over structures of median M/M^K, and median r_FS/r_0.
    kk = [np.median(col(cn, f"M_{k}") / col(cn, f"KM_{k}")) for k in ("H0", "X1", "X2")]
    m.add("xqCnotOverKosutMin", _floor_to(min(kk), 2))
    m.add("xqCnotOverKosutMax", _ceil_to(max(kk), 2))
    m.add("xqCnotFsOverRZero", np.median(col(cn, "rfs_X1") / col(cn, "r0_X1")))

    # -- the two-sided bracket on the trajectory margin -----------------
    # Range of r_FS (lower end) and m_adv (upper end) over the probed
    # controllers, in units of 10^-3, from the same file as the bracket table.
    lo = col(tvb, "r_fs")
    hi = col(tvb, "m_adv")

    # Min and max of the values as the table prints them (two decimals,
    # ordinary rounding), so prose and table agree.
    def _printed_milli(x: float) -> float:
        return float(f"{float(x) * 1e3:.2f}")

    printed_lo = np.array([_printed_milli(x) for x in lo])
    printed_hi = np.array([_printed_milli(x) for x in hi])
    m.add("xqTvBracketLowMin", float(printed_lo.min()), "{:.2f}")
    m.add("xqTvBracketLowMax", float(printed_lo.max()), "{:.2f}")
    m.add("xqTvBracketHighMin", float(printed_hi.min()), "{:.2f}")
    m.add("xqTvBracketHighMax", float(printed_hi.max()), "{:.2f}")

    # -- the constancy gap M_const - M_tv, per controller ---------------
    # Per controller, in full precision, then reduced to ensemble extremes
    # (units of 10^-3):
    #   gap_lower = max(0, M_const - m_adv)   (needs a violating trajectory)
    #   gap_upper = M_const_upper - r_FS      (needs an unsafe constant at M_upper)
    # A controller without an upper witness contributes no upper endpoint.
    gap_lo, gap_hi = [], []
    for r in tvb:
        if not int(r["adv_violated"]):
            raise SystemExit(
                f"ERROR: controller {r['controller']} has no violating "
                "trajectory, so m_adv is not a witness and the constancy "
                "gap has no lower endpoint. Rerun the adversary or drop "
                "the controller from the probed set."
            )
        lo_i = max(0.0, float(r["M_const"]) - float(r["m_adv"]))
        gap_lo.append(lo_i)
        up = float(r["M_const_upper"])
        if not np.isfinite(up):
            continue
        hi_i = up - float(r["r_fs"])
        if lo_i > hi_i:
            raise SystemExit(
                f"ERROR: controller {r['controller']} gives constancy-gap "
                f"lower endpoint {lo_i:.6e} above upper endpoint "
                f"{hi_i:.6e}. The endpoints are computed from inconsistent "
                "records; fix the inputs rather than clipping the interval."
            )
        gap_hi.append(hi_i)
    gap_lo = np.array(gap_lo)
    m.add("xqConstGapLowMin", _floor_to(gap_lo.min() * 1e3, 2), "{:.2f}")
    m.add("xqConstGapLowMax", _ceil_to(gap_lo.max() * 1e3, 2), "{:.2f}")
    if not gap_hi:
        raise SystemExit(
            "ERROR: no controller carries an unsafe constant witness, so "
            "the constancy gap has no upper endpoints. The prose range "
            "must be rewritten before these macros can be regenerated."
        )
    gap_hi = np.array(gap_hi)
    m.add("xqConstGapUpMin", _floor_to(gap_hi.min() * 1e3, 2), "{:.2f}")
    m.add("xqConstGapUpMax", _ceil_to(gap_hi.max() * 1e3, 2), "{:.2f}")
    m.add("xqConstGapBracketed", len(gap_hi), "{:d}")

    # -- how much the absorption choice actually moves ------------------
    # theta_0/theta_T in percent, and the range over structures of the drop of
    # median M^K from additive to angular absorption.
    th_T = math.acos(THRESHOLD)
    th_0 = math.acos(1.0 - eps0)
    m.add("xqAbsorptionAngleShare", 100.0 * th_0 / th_T, "{:.0f}")
    dec = [
        100.0
        * (1.0 - np.median(col(kos, f"KM_{k}")) / np.median(col(kos_add, f"KM_{k}")))
        for k in ("H0", "H1", "H2")
    ]
    m.add("xqAbsorptionMarginDropMin", _floor_to(min(dec)), "{:.0f}")
    m.add("xqAbsorptionMarginDropMax", _ceil_to(max(dec)), "{:.0f}")

    # -- state targets (appendix on state preparation) --------------------
    se = res / "state-examples-python"
    gz = read(se / "ghz_detuning_0.999.csv")
    tf = read(se / "tfim_preparation_0.999.csv")
    gd = read(se / "ghz_dephasing_0.999.csv")
    cl = read(se / "closed_limit.csv")
    sv = read(se / "state_variance_0.999.csv")
    # E1: largest n, and the gate-to-state crossing ratio at that n.
    m.add("xqStateGhzMaxN", int(gz[-1]["n"]), "{:d}")
    m.add(
        "xqStateGhzGateOverState",
        float(gz[-1]["crossing_gate_hold"]) / float(gz[-1]["crossing_state_hold"]),
    )
    # E2: one-step radius and M as a percentage of the resolved crossing
    # (both directions), and the largest evaluation count.
    frac = [
        float(r["r_one_step"]) / float(r[f"crossing_lo_{d}"])
        for r in tf
        for d in ("minus", "plus")
    ]
    m.add("xqStateTfimOneStepPctMin", 100 * min(frac), "{:.1f}")
    m.add("xqStateTfimOneStepPctMax", 100 * max(frac), "{:.0f}")
    reach = [
        float(r[f"M_{d}"]) / float(r[f"crossing_lo_{d}"])
        for r in tf
        for d in ("minus", "plus")
    ]
    m.add("xqStateTfimReachPctMin", 100 * min(reach), "{:.2f}")
    m.add(
        "xqStateTfimEvalsMax",
        max(max(int(r["evals_minus"]), int(r["evals_plus"])) for r in tf),
        "{:d}",
    )
    # E4: GHZ dephasing, one-step radius over the analytic crossing.
    ratio = [float(r["r_one_step"]) / float(r["crossing"]) for r in gd]
    m.add("xqStateDephRatioMin", min(ratio), "{:.4f}")
    # Closed limit on the chain structures: decade of the closed-form excess
    # over the spread, and the solver-free excess in percent.
    excess = max(float(r["closed_form_certified"]) / float(r["spread"]) - 1 for r in cl)
    m.add("xqStateClosedExcessExp", int(np.floor(np.log10(excess))), "{:d}")
    m.add(
        "xqStateFreeExcessPct",
        100 * max(float(r["free_certified"]) / float(r["spread"]) - 1 for r in cl),
        "{:.2f}",
    )
    # E3: integrated state-dependent speed over C^st, range in percent.
    sr = [float(r["int_sigma"]) / float(r["C_state"]) for r in sv]
    m.add("xqStateSigmaPctMin", 100 * min(sr), "{:.0f}")
    m.add("xqStateSigmaPctMax", 100 * max(sr), "{:.0f}")

    # -- targeted algorithm tests ----------------------------------------
    # Crosstalk gains at the smallest kappa, smallest boundary fidelity,
    # revival, touching and noisy-band ray cases.
    at = res / "algorithm-tests-python"
    ct = read(at / "crosstalk_0.999.csv")
    ry = {r["case"]: r for r in read(at / "rays_0.999.csv")}
    kap = sorted({float(r["kappa"]) for r in ct})
    gain_small = np.median(
        [float(r["gain_gauge"]) for r in ct if float(r["kappa"]) == kap[0]]
    )
    m.add("xqCrosstalkKappaMin", kap[0], "{:g}")
    m.add("xqCrosstalkGainGauge", gain_small, "{:.0f}")
    m.add(
        "xqCrosstalkGainAng",
        np.median([float(r["gain_ang"]) for r in ct if float(r["kappa"]) == kap[0]]),
        "{:.0f}",
    )
    m.add(
        "xqCrosstalkMinF",
        min(
            min(float(r["minF_gauge_boundary"]), float(r["minF_ang_boundary"]))
            for r in ct
        ),
        "{:.5f}",
    )
    m.add("xqCrosstalkChecked", len(ct), "{:d}")
    m.add("xqRevivalIslandLo", float(ry["revival_angular"]["island_lo"]), "{:.2f}")
    m.add("xqRevivalFirst", float(ry["revival_angular"]["first_unsafe"]), "{:.4f}")
    m.add("xqTouchM", float(ry["touch"]["M"]), "{:.4f}")
    m.add("xqTouchUpper", float(ry["touch"]["M_upper"]), "{:.2f}")
    m.add("xqTouchEvals", int(ry["touch"]["n_evals"]), "{:d}")
    over = float(ry["noisy_band0"]["M"]) / float(ry["noisy_band0"]["first_unsafe"]) - 1
    m.add("xqNoisyOvershootExp", int(np.floor(np.log10(over))), "{:d}")
    m.add("xqNoisyUnresolved", int(ry["noisy_band1e-09"]["n_unresolved"]), "{:d}")

    # -- bracket audit and cost ------------------------------------------
    # Evaluation band, bracket widths, angular vs precursor evaluation counts,
    # and median timings with the CPU name.
    ba_dir = res / "bracket-audit-python"
    ba = read(ba_dir / "brackets_0.999.csv")
    band = max(float(r["band"]) for r in ba)
    m.add(
        "xqAuditBand",
        f"10^{{{int(round(np.log10(band)))}}}",
        raw=band,
    )
    m.add(
        "xqAuditRays",
        sum(1 for r in ba if r["rule"] == "angular" and float(r["band"]) == 0),
        "{:d}",
    )
    wb = np.array(
        [
            float(r["rel_width"])
            for r in ba
            if r["rule"] == "angular" and float(r["band"]) == band
        ]
    )
    for name, v in (("Med", np.median(wb)), ("Max", wb.max())):
        e = int(np.floor(np.log10(v)))
        m.add(
            f"xqAuditWidthBand{name}", f"{v / 10**e:.1f}\\times10^{{{e}}}", raw=float(v)
        )
    ang = {
        (r["controller"], r["direction"]): r
        for r in ba
        if r["rule"] == "angular" and float(r["band"]) == 0
    }
    pre = [r for r in ba if r["rule"] == "precursor" and float(r["band"]) == 0]
    no_more = sum(
        int(ang[(r["controller"], r["direction"])]["n_evals"]) <= int(r["n_evals"])
        for r in pre
    )
    saving = np.median(
        [
            (int(r["n_evals"]) - int(ang[(r["controller"], r["direction"])]["n_evals"]))
            / int(r["n_evals"])
            for r in pre
        ]
    )
    m.add("xqAuditPrecursorRays", len(pre), "{:d}")
    m.add("xqAuditNoMorePct", 100 * no_more / len(pre), "{:.0f}")
    m.add("xqAuditSavingPct", 100 * saving, "{:.1f}")
    tm = read(ba_dir / "timing_0.999.csv")
    m.add("xqTimeRepeats", int(tm[0]["repeats"]), "{:d}")
    m.add("xqTimeControllers", len(tm), "{:d}")
    m.add("xqTimePreprocMs", 1e3 * np.median(col(tm, "t_preproc_med")), "{:.1f}")
    m.add("xqTimeEvalMs", 1e3 * np.median(col(tm, "t_eval_med")), "{:.2f}")
    m.add("xqTimeDirS", np.median(col(tm, "t_dir_med")), "{:.2f}")
    iqr_rel = max(float(r["t_dir_iqr"]) / float(r["t_dir_med"]) for r in tm)
    m.add("xqTimeDirSpreadPct", 100 * iqr_rel, "{:.1f}")
    env = json.loads((ba_dir / "environment.json").read_text())
    m.add("xqTimeCpu", env["cpu"].replace(" Processor", ""), raw=1.0)

    out = res / "paper-xqrm" / "macros.tex"
    n = m.write(out)
    if args.show:
        for name, text, raw, _ in m.items:
            print(f"  \\{name:28s} = {text:>10s}   ({raw})")
    print(f"wrote {n} macros to {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
