#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 F. C. Langbein <frank@langbein.org>
# SPDX-FileCopyrightText: (C) 2026 S. P. O'Neil <sean.oneil@westpoint.edu>
# SPDX-FileCopyrightText: (C) 2026 S. Schirmer <s.m.shermer@gmail.com>
# SPDX-FileCopyrightText: (C) 2026 C. A. Weidner <c.weidner@bristol.ac.uk>
# SPDX-FileCopyrightText: (C) 2026 E. A. Jonckheere <jonckhee@usc.edu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Build the case-study tables of the xQRM paper from the driver results.

Inputs: driver CSVs under results/ -- multiparameter-margin-python
(multiparam_0.999_angular, joint_gauge, tv_bracket), time-bandwidth-bound-python
(kosut_comparison_0.999_angular[_tv], validity_0.999[_tv], fs_validity),
single-qubit-python, cnot-python (cnot_margins, robust_vs_nominal,
duration_sweep), scaling-python, lindblad-margin-python (open_amp,
open_margins, open_threshold_sweep), state-examples-python,
algorithm-tests-python (crosstalk, rays) and bracket-audit-python (brackets).

Output: results/paper-xqrm/tables/tab_*.tex (tabular bodies), copied into
the paper repository by "make sync-xQRM". An absent input is an error unless
--allow-missing is given, in which case that table is skipped.

Usage: python3 scripts/gen_paper_xqrm_tables.py [--allow-missing]"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from _drivers import REFINEMENTS
from _paper import col, configure, have, read

ROOT = Path(__file__).resolve().parents[1]


def fmt(x, sig=3):
    """``x`` as a LaTeX math-mode cell in scientific notation.

    An exponent of zero is omitted, as is the sign of a positive exponent.
    """
    mant, _, exp = f"{x:.{sig - 1}e}".partition("e")
    e = int(exp)
    # Returned in math mode, since the table cells are plain text.
    if e == 0:
        return f"${mant}$"
    return f"${mant} \\times 10^{{{e}}}$"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--allow-missing",
        action="store_true",
        help="skip artefacts whose inputs are absent (development only)",
    )
    args = ap.parse_args()
    res = ROOT / "results"
    configure(res, args.allow_missing)
    out = ROOT / "results" / "paper-xqrm" / "tables"
    out.mkdir(parents=True, exist_ok=True)

    # Multiparameter margins from the angular-continuation run.
    mp = read(res / "multiparameter-margin-python/multiparam_0.999_angular.csv")
    # M^K with angular eps_0 absorption; the _tv file holds M^K_tv.
    kos = read(res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular.csv")
    kos_tv = read(
        res / "time-bandwidth-bound-python/kosut_comparison_0.999_angular_tv.csv"
    )
    tvb = read(res / "multiparameter-margin-python/tv_bracket_0.999.csv")

    dir_names = [c[2:] for c in mp[0] if c.startswith("M_")]
    M_dirs = np.array([[float(r[f"M_{n}"]) for n in dir_names] for r in mp])
    M_worst, M_best = M_dirs.min(axis=1), M_dirs.max(axis=1)

    # Table: single-qubit pi-pulse compared with analytic truth.
    sq_csv = res / "single-qubit-python/single_qubit_0.999.csv"
    if have(sq_csv, out / "tab_singlequbit.tex"):
        sq = read(sq_csv)
        with (out / "tab_singlequbit.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccccccc}\n\\hline\n")
            f.write(
                "structure & $M$ & $\\delta^\\ast$ & $r_0$ & "
                "$r_{\\mathrm{FS}}$ & $m_{\\mathrm{adv}}$ & $M^K$ & "
                "$M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ \\\\\n\\hline\n"
            )
            for r in sq:
                f.write(
                    f"{r['structure']} & {float(r['M']):.5f} & "
                    f"{float(r['delta_star']):.5f} & "
                    f"{float(r['r0']):.5f} & {float(r['r_fs']):.5f} & "
                    f"{float(r['m_adv']):.5f} & {float(r['KM']):.5f} & "
                    f"{float(r['KM_tv']):.5f} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_singlequbit.tex")

    # Table: CNOT transfer study (medians taken over the synthesised ensemble).
    cnot_csv = res / "cnot-python/cnot_margins_0.999.csv"
    if have(cnot_csv, out / "tab_cnot.tex"):
        cn = read(cnot_csv)
        with (out / "tab_cnot.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lcccccc}\n\\hline\n")
            f.write(
                "structure & $M$ & $r_0$ & $r_{\\mathrm{FS}}$ & "
                "$M/M^K$ & $r_{\\mathrm{FS}}/M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ & "
                "ratio $>1$ \\\\\n\\hline\n"
            )
            for tag, lab in (("H0", "drift"), ("X1", "$X_1$"), ("X2", "$X_2$")):
                M = col(cn, f"M_{tag}")
                r0 = col(cn, f"r0_{tag}")
                rfs = col(cn, f"rfs_{tag}")
                KM = col(cn, f"KM_{tag}")
                KMtv = col(cn, f"KMtv_{tag}")
                f.write(
                    f"{lab} & {fmt(np.median(M))} & {fmt(np.median(r0))} & "
                    f"{fmt(np.median(rfs))} & {np.median(M / KM):.2f} & "
                    f"{np.median(rfs / KMtv):.2f} & "
                    f"{int((rfs > KMtv).sum())}/{len(rfs)} \\\\\n"
                )
            Mg = col(cn, "M_gamma")
            gs = col(cn, "gamma_star")
            f.write("\\hline\n")
            f.write(
                f"dephasing rate & {fmt(np.median(Mg))} & & & & "
                f"$\\gamma^\\ast/M_\\gamma$: {np.median(gs / Mg):.3f} & \\\\\n"
            )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_cnot.tex")

    # Table: multi-parameter geometry summary (medians over the ensemble).
    with (out / "tab_multiparam.tex").open("w") as f:
        f.write("% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n")
        f.write("\\begin{tabular}{lccc}\n\\hline\n")
        f.write("quantity & median & min & max \\\\\n\\hline\n")
        for label, v in [
            ("polytope inradius ($\\ell^2$)", col(mp, "inradius_l2")),
            ("polytope inradius ($\\ell^\\infty$ box)", col(mp, "inradius_linf")),
            ("worst sampled directional margin $M(d)$ (of 14)", M_worst),
            ("best sampled directional margin $M(d)$", M_best),
            ("anisotropy $\\max_d M/\\min_d M$", M_best / M_worst),
            (
                "iteration gain $\\min_d M(d)/$inradius",
                M_worst / col(mp, "inradius_l2"),
            ),
        ]:
            f.write(
                f"{label} & {fmt(np.median(v))} & {fmt(v.min())} & {fmt(v.max())} \\\\\n"
            )
        f.write("\\hline\n\\end{tabular}\n")

    # Table: combined-structure gauge region against the cross-polytope.
    jg_csv = res / "multiparameter-margin-python/joint_gauge_0.999.csv"
    if have(jg_csv, out / "tab_gauge.tex"):
        jg = read(jg_csv)
        with (out / "tab_gauge.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccc}\n\\hline\n")
            f.write("quantity & median & min & max \\\\\n\\hline\n")
            for label, v in [
                ("gauge/polytope, diagonal directions", col(jg, "diag_gain_med")),
                (
                    "gauge/polytope, certified Euclidean inradius",
                    col(jg, "inradius_gain_cert"),
                ),
                (
                    "gauge/polytope, sampled inradius estimate",
                    col(jg, "inradius_gain_est"),
                ),
                ("certified gauge inradius", col(jg, "inradius_gauge_cert")),
                (
                    "trajectory vertex-gauge / separable, equal-budget box",
                    col(jg, "traj_gain"),
                ),
                (
                    "angular gauge / joint gauge, diagonal directions",
                    col(jg, "ang_diag_gain"),
                ),
                (
                    "angular gauge / joint gauge, certified inradius",
                    col(jg, "ang_inradius_gain"),
                ),
            ]:
                f.write(
                    f"{label} & {fmt(np.median(v))} & {fmt(v.min())} & "
                    f"{fmt(v.max())} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_gauge.tex")

    # Table: r_0, r_FS, M, M^K (constant class) and M^K_tv (trajectory class);
    # r_FS from fs_validity.
    fs = read(res / "time-bandwidth-bound-python/fs_validity_0.999.csv")
    with (out / "tab_tv.tex").open("w") as f:
        f.write("% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n")
        f.write("\\begin{tabular}{lccccccc}\n\\hline\n")
        f.write(
            "structure & $r_0$ & $r_{\\mathrm{FS}}$ & $M$ & $M^K$ & "
            "$M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ & $M/M^K$ & "
            "$r_{\\mathrm{FS}}/M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ \\\\\n\\hline\n"
        )
        for j, tag in enumerate(("H0", "H1", "H2")):
            r0 = col(mp, f"r0_{tag}")
            rfs_rows = [r for r in fs if r["structure"] == tag]
            rfs = np.array([float(r["r_fs"]) for r in rfs_rows])
            M = np.minimum(col(mp, f"M_+e{j}"), col(mp, f"M_-e{j}"))
            MK = col(kos, f"KM_{tag}")
            MKtv = col(kos_tv, f"KM_{tag}")
            n = len(rfs)  # possibly partial while the FS run is live
            f.write(
                f"$H_{j}$ & {fmt(np.median(r0))} & {fmt(np.median(rfs))} & "
                f"{fmt(np.median(M))} & {fmt(np.median(MK))} & "
                f"{fmt(np.median(MKtv))} & {np.median(M / MK):.2f} & "
                f"{np.median(rfs / MKtv[:n]):.2f} \\\\\n"
            )
        f.write("\\hline\n\\end{tabular}\n")

    # Table: trajectory brackets [r_FS, m_adv] and constant-class brackets
    # [M, M_upper] from tv_bracket; r_FS must agree with fs_validity (H1).
    rfs_h1 = {
        int(r["controller"]): float(r["r_fs"]) for r in fs if r["structure"] == "H1"
    }
    with (out / "tab_tvbracket.tex").open("w") as f:
        f.write("% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n")
        f.write("\\begin{tabular}{lcccccc}\n\\hline\n")
        # Entries are in units of 10^-3, stated once in the header.
        f.write(
            "controller & $r_{\\mathrm{FS}}$ & $m_{\\mathrm{adv}}$ & "
            "$M$ & $M_{\\mathrm{upper}}$ & gap lower & gap upper "
            "\\\\\n & \\multicolumn{6}{c}{(all in units of $10^{-3}$)} "
            "\\\\\n\\hline\n"
        )
        for r in tvb:
            M, ub = float(r["M_const"]), float(r["m_adv"])
            lo = float(r["r_fs"])
            ref = rfs_h1.get(int(r["controller"]))
            if ref is not None and abs(ref - lo) > 1e-9 * max(1.0, abs(ref)):
                raise SystemExit(
                    f"ERROR: controller {r['controller']} has r_FS = {lo:.9e} in "
                    f"the bracket record and {ref:.9e} in the validity record. "
                    "The two runs disagree; the records must be reconciled."
                )
            mup = float(r["M_const_upper"])
            g_lo = r["gap_lower"]
            g_hi = r["gap_upper"]

            def milli(x):
                return f"{x * 1e3:.2f}"

            cell_lo = milli(float(g_lo)) if g_lo != "" else "n/a"
            cell_hi = milli(float(g_hi)) if g_hi != "" else "n/a"
            f.write(
                f"{r['controller']} & {milli(lo)} & {milli(ub)} & {milli(M)} & "
                + (milli(mup) if np.isfinite(mup) else "n/a")
                + f" & {cell_lo} & {cell_hi} \\\\\n"
            )
        f.write("\\hline\n\\end{tabular}\n")

    # Table: adversarial attacks on M^K (constant class, an over-claim probe)
    # and on M^K_tv (trajectory class, a genuine validity test). One line per
    # (structure, class): worst fidelity at budget M and at 1.05 M over the
    # control grid and the x4-refined grid, plus violation counts at budget M.
    def _val_rows(val, label):
        # Grid labels ("grid", "x4", "x16", ...) read off the header so
        # the table follows the refinement set of the attack script.
        grids = [
            h[len("Fmin_m1_") :] for h in val[0].keys() if h.startswith("Fmin_m1_")
        ]
        lines = []
        for tag in ("H0", "H1", "H2"):
            rows_t = [
                r
                for r in val
                if r["structure"] == tag and r["KM"] and float(r["KM"]) > 0
            ]
            fmin1 = np.array(
                [min(float(r[f"Fmin_m1_{g}"]) for g in grids) for r in rows_t]
            )
            fmin105 = np.array(
                [min(float(r[f"Fmin_m105_{g}"]) for g in grids) for r in rows_t]
            )
            v1 = int((fmin1 < 0.999).sum())
            lines.append(
                f"$H_{tag[1]}$, {label} & {2 * len(grids) * len(rows_t)} & "
                f"{fmin1.min():.6f} & {fmin105.min():.6f} & {v1} \\\\\n"
            )
        return lines

    def _fs_val_rows(val):
        lines = []
        for tag in ("H0", "H1", "H2"):
            rows_t = [r for r in val if r["structure"] == tag]
            fmin1 = np.array(
                [min(float(r[f"Fmin_m1_x{q}"]) for q in REFINEMENTS) for r in rows_t]
            )
            fmin105 = np.array(
                [min(float(r[f"Fmin_m105_x{q}"]) for q in REFINEMENTS) for r in rows_t]
            )
            v1 = int((fmin1 < 0.999).sum())
            lines.append(
                f"$H_{tag[1]}$, $r_{{\\mathrm{{FS}}}}$ & {6 * len(rows_t)} & "
                f"{fmin1.min():.6f} & {fmin105.min():.6f} & {v1} \\\\\n"
            )
        return lines

    val_csv = res / "time-bandwidth-bound-python/validity_0.999.csv"
    val_tv_csv = res / "time-bandwidth-bound-python/validity_0.999_tv.csv"
    fs_val_csv = res / "time-bandwidth-bound-python/fs_validity_0.999.csv"
    if have(val_csv, out / "tab_validity.tex"):
        with (out / "tab_validity.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lcccc}\n\\hline\n")
            f.write(
                "structure, budget $m$ & attacks & $\\min\\F$ at $m$ & "
                "$\\min\\F$ at $1.05\\,m$ & viol.\\ at $m$ \\\\\n\\hline\n"
            )
            for line in _val_rows(read(val_csv), "$M^K$"):
                f.write(line)
            if have(val_tv_csv):
                f.write("\\hline\n")
                for line in _val_rows(
                    read(val_tv_csv), "$M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$"
                ):
                    f.write(line)
            if have(fs_val_csv):
                f.write("\\hline\n")
                for line in _fs_val_rows(read(fs_val_csv)):
                    f.write(line)
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_validity.tex")

    # Table: amplitude damping together with joint two-rate margins.
    amp_csv = res / "lindblad-margin-python/open_amp_0.999.csv"
    if have(amp_csv, out / "tab_amp.tex"):
        am = read(amp_csv)
        with (out / "tab_amp.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccc}\n\\hline\n")
            f.write("quantity & median & min & max \\\\\n\\hline\n")
            r0_ratio = col(am, "amp_star") / col(am, "r0_amp")
            for label, v in [
                (
                    "one-step radius $r_0^{\\gamma_-}$ (amp.\\ damping)",
                    col(am, "r0_amp"),
                ),
                (
                    "iterated certified $M_{\\gamma_-}$ (amp.\\ damping)",
                    col(am, "M_amp"),
                ),
                ("reference crossing $\\gamma_-^\\ast$", col(am, "amp_star")),
                ("first-order factor $\\gamma_-^\\ast/r_0^{\\gamma_-}$", r0_ratio),
                (
                    "conservatism $\\gamma_-^\\ast/M_{\\gamma_-}$",
                    col(am, "conservatism_amp"),
                ),
                ("joint diagonal, free simplex radius", col(am, "g_cert_diag")),
                ("joint diagonal, iterated $M_{\\mathrm{diag}}$", col(am, "M_diag")),
                (
                    "conservatism $g^\\ast/M_{\\mathrm{diag}}$",
                    col(am, "conservatism_diag_iter"),
                ),
            ]:
                f.write(
                    f"{label} & {fmt(np.median(v))} & {fmt(v.min())} & "
                    f"{fmt(v.max())} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_amp.tex")

    # Table: robust-vs-nominal controller families.
    rn_csv = res / "cnot-python/robust_vs_nominal_0.999.csv"
    if have(rn_csv, out / "tab_robust.tex"):
        rn = read(rn_csv)
        with (out / "tab_robust.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lcccc}\n\\hline\n")
            f.write(
                "quantity & nominal med [IQR] & robustified med [IQR] "
                "& ratio & rob.\\ lower \\\\\n\\hline\n"
            )
            for key, lab in (
                ("M_H0", "iterated $M$, drift"),
                ("M_X1", "iterated $M$, $X_1$"),
                ("M_X2", "iterated $M$, $X_2$"),
                ("rfs_X1", "$r_{\\mathrm{FS}}$, $X_1$"),
                ("rfs_X2", "$r_{\\mathrm{FS}}$, $X_2$"),
                ("madv_X1", "$m_{\\mathrm{adv}}$, $X_1$"),
                ("madv_X2", "$m_{\\mathrm{adv}}$, $X_2$"),
            ):
                if key.startswith("madv_") and key not in rn[0]:
                    continue
                nom = {r["seed"]: float(r[key]) for r in rn if r["kind"] == "nominal"}
                rob = {r["seed"]: float(r[key]) for r in rn if r["kind"] == "robust"}
                seeds = sorted(set(nom) & set(rob))
                a = np.array([nom[k] for k in seeds])
                b = np.array([rob[k] for k in seeds])
                qa = np.percentile(a, [25, 50, 75])
                qb = np.percentile(b, [25, 50, 75])
                # Paired by seed: number of pairs where robust < nominal.
                down = int(np.sum(b < a))
                f.write(
                    f"{lab} & {fmt(qa[1])} [{fmt(qa[0])}, {fmt(qa[2])}] "
                    f"& {fmt(qb[1])} [{fmt(qb[0])}, {fmt(qb[2])}] & "
                    f"{qb[1] / qa[1]:.2f} & {down}/{len(seeds)} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_robust.tex")

    # Table: four-qubit scaling study, with cost in evaluation counts.
    sc_csv = res / "scaling-python/scaling4q_margins_0.999.csv"
    if have(sc_csv, out / "tab_scaling.tex"):
        sc = read(sc_csv)
        with (out / "tab_scaling.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccccc}\n\\hline\n")
            f.write(
                "structure & $M$ & $r_0$ & $r_{\\mathrm{FS}}$ & "
                "$M/M^K$ & $r_{\\mathrm{FS}}/M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ \\\\\n"
                "\\hline\n"
            )
            tags = ["H0"] + [f"X{q}" for q in (1, 2, 3, 4)]
            for tag in tags:
                M = col(sc, f"M_{tag}")
                r0 = col(sc, f"r0_{tag}")
                rfs = col(sc, f"rfs_{tag}")
                KM = col(sc, f"KM_{tag}")
                KMtv = col(sc, f"KMtv_{tag}")
                lab = "drift" if tag == "H0" else f"$X_{tag[1]}$"
                f.write(
                    f"{lab} & {fmt(np.median(M))} & {fmt(np.median(r0))} & "
                    f"{fmt(np.median(rfs))} & {np.median(M / KM):.2f} & "
                    f"{np.median(rfs / KMtv):.2f} \\\\\n"
                )
            f.write("\\hline\n")
            ne = col(sc, "n_evals_iter")
            f.write(
                f"\\multicolumn{{6}}{{l}}{{evaluations per "
                f"controller: iterated ${np.median(ne):.0f}$, "
                f"geometric $0$, universal $0$}} \\\\\n"
            )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_scaling.tex")

    # Table: threshold sweep of that dissipative first-order picture.
    ts_csv = res / "lindblad-margin-python/open_threshold_sweep.csv"
    if have(ts_csv, out / "tab_sweep.tex"):
        ts = read(ts_csv)
        with (out / "tab_sweep.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccc}\n\\hline\n")
            f.write(
                "channel & $\\FT = 0.99$ & $\\FT = 0.999$ & "
                "$\\FT = 0.9999$ \\\\\n\\hline\n"
            )
            for chan, lab in (
                ("dephasing", "dephasing (predicts $1$)"),
                ("amp_damping", "amplitude damping (predicts $2$)"),
            ):
                cells = []
                for ft in (0.99, 0.999, 0.9999):
                    v = np.array(
                        [
                            float(r["ratio"])
                            for r in ts
                            if r["channel"] == chan and abs(float(r["FT"]) - ft) < 1e-12
                        ]
                    )
                    # Median and count; only controllers nominally above
                    # F_T are eligible, so the cohort changes with F_T.
                    cells.append(f"{np.median(v):.4f} ({v.size})")
                f.write(f"{lab} & " + " & ".join(cells) + " \\\\\n")
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_sweep.tex")

    # Table: duration sweep of every certificate (CNOT, the structure X1).
    ds_csv = res / "cnot-python/duration_sweep_0.999.csv"
    if have(ds_csv, out / "tab_duration.tex"):
        ds = read(ds_csv)
        with (out / "tab_duration.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccccc}\n\\hline\n")
            f.write(
                "$t_f$ & $M$ & $r_0$ & $r_{\\mathrm{FS}}$ & $M^K$ & "
                "$M^{K,\\mathrm{tri}}_{\\mathrm{tv}}$ \\\\\n"
                "\\hline\n"
            )
            for tf in (4.0, 8.0, 16.0, 32.0):
                sel = [r for r in ds if abs(float(r["tf"]) - tf) < 1e-9]
                med = {
                    k: np.median([float(r[k]) for r in sel])
                    for k in ("M", "r0", "rfs", "KM", "KMtv")
                }
                f.write(
                    f"{tf:g} & {fmt(med['M'])} & {fmt(med['r0'])} & "
                    f"{fmt(med['rfs'])} & {fmt(med['KM'])} & "
                    f"{fmt(med['KMtv'])} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_duration.tex")

    # Table: open-system dephasing margins.
    open_csv = res / "lindblad-margin-python/open_margins_0.999.csv"
    if have(open_csv, out / "tab_open.tex"):
        op = read(open_csv)
        with (out / "tab_open.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lccc}\n\\hline\n")
            f.write("quantity & median & min & max \\\\\n\\hline\n")
            for label, v, digits in [
                ("iterated certified $M_\\gamma$", col(op, "M_gamma"), None),
                ("one-step $r_0^\\gamma$", col(op, "r0_gamma"), None),
                ("reference crossing $\\gamma^\\ast$", col(op, "gamma_star"), None),
                (
                    "conservatism $\\gamma^\\ast/r_0^\\gamma$",
                    col(op, "conservatism_r0"),
                    5,
                ),
            ]:
                if digits:
                    f.write(
                        f"{label} & {np.median(v):.{digits}f} & "
                        f"{v.min():.{digits}f} & {v.max():.{digits}f} "
                        f"\\\\\n"
                    )
                else:
                    f.write(
                        f"{label} & {fmt(np.median(v))} & {fmt(v.min())} & "
                        f"{fmt(v.max())} \\\\\n"
                    )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_open.tex")

    # Tables: state targets (GHZ detuning, TFIM preparation).
    se = res / "state-examples-python"
    ghz_csv = se / "ghz_detuning_0.999.csv"
    if have(ghz_csv, out / "tab_states_ghz.tex"):
        gz = read(ghz_csv)
        with (out / "tab_states_ghz.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{rcccccc}\n\\hline\n")
            f.write(
                "$n$ & $C^{\\mathrm{st}}$ & $s$ (Choi) & "
                "$r^{\\mathrm{st}} = \\delta^\\ast_{\\mathrm{st}}$ & "
                "$r_{\\mathrm{FS}}$ & $\\delta^\\ast_{\\mathrm{gate}}$ & "
                "$M$, prep.\\ and hold \\\\\n\\hline\n"
            )
            for r in gz:
                f.write(
                    f"{r['n']} & {float(r['C_state_hold']):.2f} & "
                    f"{float(r['C_choi_hold']):.2f} & "
                    f"{fmt(float(r['r_state_hold']))} & "
                    f"{fmt(float(r['r_gate_hold']))} & "
                    f"{fmt(float(r['crossing_gate_hold']))} & "
                    f"{fmt(float(r['M_all']), 4)} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_states_ghz.tex")
    tf_csv = se / "tfim_preparation_0.999.csv"
    if have(tf_csv, out / "tab_states_tfim.tex"):
        tf = read(tf_csv)
        with (out / "tab_states_tfim.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{rrcccccc}\n\\hline\n")
            f.write(
                "$L$ & $h_0$ & gap & $C_{\\mathrm{prep}}$ & $\\sigma/\\gamma$ & "
                "$r_1$ & $M_-$ (evals) & $M_+$ (evals) \\\\\n\\hline\n"
            )
            for r in tf:
                f.write(
                    f"{r['L']} & {float(r['h0']):.2f} & {fmt(float(r['gap']))} & "
                    f"{float(r['C_prep_fd']):.3f} & "
                    f"{float(r['C_prep_sigma']):.3f} & "
                    f"{fmt(float(r['r_one_step']))} & "
                    f"{float(r['M_minus']):.4f} ({r['evals_minus']}) & "
                    f"{float(r['M_plus']):.4f} ({r['evals_plus']}) \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_states_tfim.tex")

    # Table: paired reversals (robust M > nominal M_upper and robust m_adv <
    # nominal r_FS on the same seed pair), per control structure.
    rn_csv = res / "cnot-python/robust_vs_nominal_0.999.csv"
    if have(rn_csv, out / "tab_reversal.tex"):
        pairs = {}
        for r in read(rn_csv):
            pairs.setdefault(r["seed"], {})[r["kind"]] = r
        seeds = sorted(s for s, v in pairs.items() if len(v) == 2)
        with (out / "tab_reversal.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{llcccc}\n\\hline\n")
            f.write(
                "structure & pair & $M^{\\mathrm{rob}}$ & "
                "$M^{\\mathrm{nom}}_{\\mathrm{upper}}$ & "
                "$m^{\\mathrm{rob}}_{\\mathrm{adv}}$ & "
                "$r^{\\mathrm{nom}}_{\\mathrm{FS}}$ \\\\\n"
                " & & \\multicolumn{4}{c}{(all in units of $10^{-3}$)} \\\\\n"
                "\\hline\n"
            )
            for k in ("X1", "X2"):
                for i, sd in enumerate(seeds, start=1):
                    rob, nom = pairs[sd]["robust"], pairs[sd]["nominal"]
                    if float(rob[f"M_{k}"]) > float(nom[f"Mupper_{k}"]) and float(
                        rob[f"madv_{k}"]
                    ) < float(nom[f"rfs_{k}"]):
                        f.write(
                            f"${k[0]}_{k[1]}$ & {i} & "
                            f"{float(rob[f'M_{k}']) * 1e3:.2f} & "
                            f"{float(nom[f'Mupper_{k}']) * 1e3:.2f} & "
                            f"{float(rob[f'madv_{k}']) * 1e3:.2f} & "
                            f"{float(nom[f'rfs_{k}']) * 1e3:.2f} \\\\\n"
                        )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_reversal.tex")

    # Tables: targeted algorithm tests (crosstalk, rays).
    at = res / "algorithm-tests-python"
    ct_csv = at / "crosstalk_0.999.csv"
    if have(ct_csv, out / "tab_crosstalk.tex"):
        ct = read(ct_csv)
        with (out / "tab_crosstalk.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{rcccc}\n\\hline\n")
            f.write(
                "$\\kappa$ & Gram correlation & gauge gain & angular gain & "
                "min.\\ $\\F$ on boundaries \\\\\n\\hline\n"
            )
            for kap in sorted({float(r["kappa"]) for r in ct}, reverse=True):
                rr = [r for r in ct if float(r["kappa"]) == kap]
                med = lambda key, rr=rr: float(np.median([float(r[key]) for r in rr]))  # noqa: E731
                minF = min(
                    min(float(r["minF_gauge_boundary"]), float(r["minF_ang_boundary"]))
                    for r in rr
                )
                f.write(
                    f"{kap:g} & {med('gram_corr_max'):.4f} & "
                    f"{med('gain_gauge'):.2f} & {med('gain_ang'):.2f} & "
                    f"{minF:.6f} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_crosstalk.tex")
    ry_csv = at / "rays_0.999.csv"
    if have(ry_csv, out / "tab_rays.tex"):
        labels = {
            "revival_lipschitz": "revival, Lipschitz step",
            "revival_angular": "revival, angular step",
            "touch": "touching curve",
            "noisy_band0": "noisy, no band",
            "noisy_band1e-09": "noisy, band $10^{-9}$",
        }
        with (out / "tab_rays.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{lcccccc}\n\\hline\n")
            f.write(
                "ray & first unsafe & $M$ & $M_{\\mathrm{upper}}$ & status & "
                "unresolved & evaluations \\\\\n\\hline\n"
            )
            for r in read(ry_csv):
                f.write(
                    f"{labels[r['case']]} & {float(r['first_unsafe']):.8f} & "
                    f"{float(r['M']):.8f} & {float(r['M_upper']):.8f} & "
                    f"{r['reason']} & {r['n_unresolved']} & {r['n_evals']} \\\\\n"
                )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_rays.tex")

    # Table: bracket audit -- brackets achieved at the requested relative
    # width, without and with the evaluation band.
    ba_csv = res / "bracket-audit-python/brackets_0.999.csv"
    if have(ba_csv, out / "tab_audit.tex"):
        ba = read(ba_csv)
        with (out / "tab_audit.tex").open("w") as f:
            f.write(
                "% Auto-generated by scripts/gen_paper_xqrm_tables.py -- do not edit\n"
            )
            f.write("\\begin{tabular}{llrccccc}\n\\hline\n")
            f.write(
                "rule & band & rays & bracketed & unresolved & "
                "median width & max.\\ width & median evaluations \\\\\n\\hline\n"
            )
            names = {"angular": "angular, all rays", "precursor": "scalar, axes"}
            for rule in ("angular", "precursor"):
                for band in sorted({float(r["band"]) for r in ba}):
                    rr = [
                        r for r in ba if r["rule"] == rule and float(r["band"]) == band
                    ]
                    w = np.array([float(r["rel_width"]) for r in rr])
                    ev = np.array([int(r["n_evals"]) for r in rr])
                    bl = "off" if band == 0 else fmt(band, 1)
                    f.write(
                        f"{names[rule]} & {bl} & {len(rr)} & "
                        f"{sum(r['reason'] == 'bracketed' for r in rr)} & "
                        f"{sum(r['reason'] == 'unresolved' for r in rr)} & "
                        f"{fmt(float(np.median(w)), 2)} & {fmt(float(w.max()), 2)} & "
                        f"{int(np.median(ev))} \\\\\n"
                    )
            f.write("\\hline\n\\end{tabular}\n")
        print("wrote tab_audit.tex")
    print("wrote tab_multiparam.tex, tab_tv.tex, tab_tvbracket.tex")


if __name__ == "__main__":
    main()
