# SPDX-FileCopyrightText: (C) 2026 F. C. Langbein <frank@langbein.org>
# SPDX-FileCopyrightText: (C) 2026 S. P. O'Neil <sean.oneil@westpoint.edu>
# SPDX-FileCopyrightText: (C) 2026 S. Schirmer <s.m.shermer@gmail.com>
# SPDX-FileCopyrightText: (C) 2026 C. A. Weidner <c.weidner@bristol.ac.uk>
# SPDX-FileCopyrightText: (C) 2026 E. A. Jonckheere <jonckhee@usc.edu>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Fidelity-based robustness margins for finite-time quantum control."""

from .core import (
    dU_dmu_exact,
    dU_dmu_integral,
    gauss_legendre_01,
    segment_eig,
    segment_propagator,
    DU_METHODS,
    MARGIN_METHODS,
    MARGIN_STATUS,
    ROOT_SOLVERS,
    MarginResult,
    dH_structure,
    differential_sensitivity,
    fidelity_vs_delta,
    gate_fidelity,
    iterative_margin,
    lipschitz_constant,
    load_controllers,
    load_problem,
    make_fidelity_fn,
    perturbed_hamiltonians,
    propagator,
    structure_constant,
    traceless,
)
from .kosut import (
    ABSORPTIONS,
    T_OMEGA_MAX,
    UncertaintyRates,
    fidelity_bound,
    fidelity_bound_at,
    effective_threshold,
    threshold_time_bandwidth,
    time_bandwidth,
    uncertainty_rates,
)
from .kosut import margin as kosut_margin
from .optimize import (
    OptimizeResult,
    fidelity_and_gradient,
    optimize_controller,
    pack_controls,
    unpack_controls,
)
from .plotting import (
    apply_plot_style,
    save_fig,
    log10_axis,
    plot_fidelity_error_sweeps,
    plot_margins_vs_index,
    plot_margins_vs_sensitivity,
)

# The xQRM extensions: joint static regions, the Choi-Fubini-Study
# trajectory certificate, Lindblad rate margins, the verification harness,
# and the synthesis that builds the CNOT and four-qubit ensembles.
from .lengthspace import (
    PathGauge,
    angle_budget,
    interval_grams,
    margin_from,
    refine,
)
from .multiparam import (
    AngularGauge,
    JointGauge,
    SafePolytope,
    SafeUnion,
    angular_gauge,
    axis_directions,
    diagonal_directions,
    directional_margin,
    joint_gauge,
    make_multiparam_fidelity_fn,
    make_ray_fn,
    safe_polytope,
    sphere_directions,
    structure_constants,
)
from .timevarying import (
    FSMargin,
    TVBracket,
    adversarial_upper_bound,
    fs_margin,
    fs_margin_joint,
    tv_bracket,
    tv_fidelity_and_gradient,
    uniform_margin,
)
from .lindblad import (
    DiamondNorm,
    VerificationFailure,
    average_gate_fidelity,
    channel,
    choi_matrix,
    choi_roundtrip_exact,
    coherence_time,
    common_rate_local_dnorm,
    dephasing_time,
    diamond_norm,
    diamond_norm_free,
    dissipator,
    frechet_derivative,
    generator,
    hamiltonian_superop,
    make_open_fidelity_fn,
    open_margin,
    open_structure_constants,
    rate_lipschitz,
    rates_from_times,
    relaxation_time,
    process_fidelity,
    superop_from_choi,
    unitary_superop,
)
from .synthesis import (
    GrapeResult,
    fidelity_and_control_gradient,
    grape,
    grape_ensemble,
    grape_robust,
)
from .berberich import (
    BerberichMargin,
    UNCERTAINTIES,
)
from .verify import (
    CheckReport,
    check_absorption,
    check_constant_margin,
    check_fs_angle,
    check_lipschitz_pairs,
    check_metric_triangle,
    check_polytope,
    check_trajectory_certificate,
    check_tv_slope,
    fidelity_cross_check,
    unitarity_defect,
)
from .berberich import margin as berberich_margin

__all__ = [
    "dU_dmu_exact",
    "dU_dmu_integral",
    "gauss_legendre_01",
    "segment_eig",
    "segment_propagator",
    "propagator",
    "gate_fidelity",
    "lipschitz_constant",
    "structure_constant",
    "traceless",
    "perturbed_hamiltonians",
    "dH_structure",
    "differential_sensitivity",
    "iterative_margin",
    "DU_METHODS",
    "MARGIN_METHODS",
    "MARGIN_STATUS",
    "ROOT_SOLVERS",
    "MarginResult",
    "fidelity_vs_delta",
    "load_problem",
    "load_controllers",
    "make_fidelity_fn",
    "T_OMEGA_MAX",
    "UncertaintyRates",
    "uncertainty_rates",
    "time_bandwidth",
    "fidelity_bound",
    "fidelity_bound_at",
    "effective_threshold",
    "threshold_time_bandwidth",
    "ABSORPTIONS",
    "kosut_margin",
    "fidelity_and_gradient",
    "optimize_controller",
    "OptimizeResult",
    "pack_controls",
    "unpack_controls",
    "apply_plot_style",
    "save_fig",
    "log10_axis",
    "plot_margins_vs_index",
    "plot_margins_vs_sensitivity",
    "plot_fidelity_error_sweeps",
    "AngularGauge",
    "BerberichMargin",
    "CheckReport",
    "DiamondNorm",
    "FSMargin",
    "GrapeResult",
    "JointGauge",
    "PathGauge",
    "SafePolytope",
    "SafeUnion",
    "TVBracket",
    "UNCERTAINTIES",
    "adversarial_upper_bound",
    "angle_budget",
    "angular_gauge",
    "average_gate_fidelity",
    "axis_directions",
    "berberich_margin",
    "channel",
    "check_absorption",
    "check_constant_margin",
    "check_fs_angle",
    "check_lipschitz_pairs",
    "check_metric_triangle",
    "check_polytope",
    "check_trajectory_certificate",
    "check_tv_slope",
    "choi_matrix",
    "choi_roundtrip_exact",
    "superop_from_choi",
    "coherence_time",
    "common_rate_local_dnorm",
    "dephasing_time",
    "relaxation_time",
    "rates_from_times",
    "VerificationFailure",
    "diagonal_directions",
    "diamond_norm",
    "diamond_norm_free",
    "directional_margin",
    "dissipator",
    "fidelity_and_control_gradient",
    "fidelity_cross_check",
    "frechet_derivative",
    "fs_margin",
    "fs_margin_joint",
    "generator",
    "grape",
    "grape_ensemble",
    "grape_robust",
    "hamiltonian_superop",
    "interval_grams",
    "joint_gauge",
    "make_multiparam_fidelity_fn",
    "make_open_fidelity_fn",
    "make_ray_fn",
    "margin_from",
    "open_margin",
    "open_structure_constants",
    "rate_lipschitz",
    "process_fidelity",
    "refine",
    "safe_polytope",
    "sphere_directions",
    "structure_constants",
    "traceless",
    "tv_bracket",
    "tv_fidelity_and_gradient",
    "uniform_margin",
    "unitarity_defect",
    "unitary_superop",
]

__version__ = "1.1.0"
